const translations = {
            // General
            headerTitle: {vi: "Alpha AI Color Lab", en: "Alpha AI Color Lab"},
            navPictureProfile: {vi: "Picture Profile", en: "Picture Profile"},
            navRecipeFormulas: {vi:"Công thức màu", en:"Color Recipes"},
            navCreativeLooks: {vi:"Creative Look", en:"Creative Look"},
            navFeaturedPhotos: {vi: "Ảnh nổi bật", en: "Featured Photos"},
            navExplain: {vi:"Giải thích (PP)", en:"Guide (PP)"},
            noteTitle: {vi:"Lưu ý quan trọng", en:"Important Note"},
            footerText: {vi: "Phát triển bởi Sony Alpha Vietnam.", en: "Developed by Sony Alpha Vietnam."},

            // Home / Quiz
            landingTitle: {vi:"Tìm màu sắc của riêng bạn.", en:"Find Your Signature Color."},
            landingSubtitle: {vi:"Trả lời vài câu hỏi để khám phá công thức màu được AI tạo ra dành riêng cho tâm trạng và phong cách của bạn.", en:"Answer a few questions to discover a unique color recipe, tailored by AI to your mood and style."},
            startQuizBtn: {vi:"Khám phá màu của bạn", en:"Discover Your Color"},
            quizResultTitle: {vi: "AI đề xuất 2 lựa chọn cho bạn:", en: "AI suggests 2 options for you:"},
            viewInLibraryBtn: {vi: "Xem trong thư viện", en: "View in Library"},
            loadingAnalyze: {vi: "Đang phân tích lựa chọn...", en: "Analyzing your choices..."},
            
            // Recipe Formulas
            sidebarTitle: {vi: "Công thức Picture Profile", en: "Picture Profile Recipes"},
            searchInputPlaceholder: {vi: "🔍 Tìm công thức...", en: "🔍 Search recipes..."},
            filterType: {vi: "Loại", en: "Type"},
            filterTypeColor: {vi: "Màu", en: "Color"},
            filterTypeBW: {vi: "Trắng Đen", en: "B&W"},
            filterContrast: {vi: "Tương phản", en: "Contrast"},
            filterSaturation: {vi: "Bão hòa", en: "Saturation"},
            filterHigh: {vi: "Cao", en: "High"},
            filterMedium: {vi: "Vừa", en: "Med"},
            filterLow: {vi: "Thấp", en: "Low"},
            filterSort: {vi: "Sắp xếp theo", en: "Sort by"},
            sortDefault: {vi: "Mặc định", en: "Default"},
            sortNameAZ: {vi: "Tên A-Z", en: "Name A-Z"},
            sortContrastHL: {vi: "Tương phản: Cao-Thấp", en: "Contrast: High-Low"},
            sortSaturationHL: {vi: "Bão hòa: Cao-Thấp", en: "Saturation: High-Low"},
            compareBtn: {vi: "So sánh bằng AI", en: "Compare with AI"},
            recipeDetailWelcomeTitle: {vi: "Thư viện màu Tương tác", en: "Interactive Color Library"},
            recipeDetailWelcomeText: {vi: "Khám phá các công thức màu Picture Profile một cách trực quan. Nhấp vào một điểm trên biểu đồ hoặc một công thức trong danh sách để xem chi tiết.", en: "Explore Picture Profile color recipes visually. Click a point on the chart or a recipe in the list to see details."},
            whiteBalanceTitle: {vi: "Cân bằng trắng (WB)", en: "White Balance (WB)"},
            recipeSettingsTitle: {vi: "Cài đặt Chính", en: "Main Settings"},
            colorDepthTitle: {vi: "Độ sâu màu", en: "Color Depth"},
            detailTitle: {vi: "Chi tiết", en: "Detail"},
            aiTuningTitle: {vi: "Tinh chỉnh bằng AI", en: "AI Fine-Tuning"},
            aiTuningPlaceholder: {vi: "Nhập yêu cầu của bạn ở đây... (ví dụ: 'làm cho màu ấm hơn và trong hơn')", en: "Enter your request here... (e.g., 'make it warmer and clearer')"},
            aiTuningBtn: {vi: "Tạo bằng AI", en: "Generate with AI"},
            aiResultTitle: {vi: "Công thức đã được AI tinh chỉnh:", en: "AI-Adjusted Recipe:"},
            compareWithOriginalBtn: {vi: "So sánh với bản gốc", en: "Compare with Original"},
            aiSuggestionTitle: {vi: "Gợi ý của AI:", en: "AI Suggestion:"},
            aiSuggestionText: {vi: "Dựa trên yêu cầu của bạn, công thức này có vẻ phù hợp hơn: ", en: "Based on your request, this recipe might be a better fit: "},
            comparisonModalTitle: {vi: "So sánh Công thức", en: "Recipe Comparison"},
            comparisonLoading: {vi: "AI đang phân tích và so sánh...", en: "AI is analyzing and comparing..."},
            colorChartTitle: {vi: "Biểu đồ Màu", en: "Color Chart"},
            bwChartTitle: {vi: "Biểu đồ Đơn sắc (B&W)", en: "Monochrome (B&W) Chart"},
            axisTonality: {vi: "Tương phản (← Mềm | Cứng →)", en: "Tonality (← Soft | Hard →)"},
            axisSaturation: {vi: "Độ bão hòa (← Thấp | Cao →)", en: "Saturation (← Low | High →)"},
            axisChroma: {vi: "Độ sâu màu (← Thấp | Cao →)", en: "Chroma Depth (← Low | High →)"},
            backToListBtn: {vi: "← Quay lại danh sách", en: "← Back to list"},

            // Featured Photos
            featuredTitle: {vi: "Ảnh Nổi Bật từ Cộng Đồng", en: "Featured Photos from the Community"},
            featuredCta: {vi: "Cùng nhau xây dựng một thư viện ảnh đầy cảm hứng! Hãy chia sẻ những tác phẩm bạn chụp bằng các công thức từ Alpha AI Color Lab. Ảnh được chọn sẽ xuất hiện tại đây để vinh danh.", en: "Let's build an inspiring gallery together! Share your creations shot with recipes from the Alpha AI Color Lab. Selected photos will be featured here."},
            featuredAlbumBtn: {vi: "Xem Album & Đóng góp Ảnh", en: "View Album & Contribute Photos"},
            contributeTitle: {vi: "Hoặc Tải lên Ảnh của Bạn", en: "Or Upload Your Photo"},
            contributeDesc: {vi: "Tải lên ảnh của bạn để chia sẻ ẩn danh. (Chỉ mang tính minh hoạ, ảnh sẽ không được lưu trữ).", en: "Upload your photo to share anonymously. (For demonstration purposes only, photos will not be saved)."},
            uploadBtn: {vi: "Chọn Ảnh từ Máy tính", en: "Choose Photo From Computer"},
            
            // Creative Looks
            creativeLookHeader: {vi: "Khám Phá Creative Look", en: "Exploring Creative Looks"},
            creativeLookSubtitle: {vi: "Tạo nên thần thái cho bức ảnh ngay tại máy với 10 tuỳ chọn Creative Look có sẵn và khả năng tuỳ chỉnh sâu. Đây là tính năng mới hơn so với Creative Style trên các dòng máy cũ.", en: "Instantly create the mood for your photos in-camera with 10 pre-set Creative Looks and deep customization options. This is a newer feature compared to Creative Style on older models."},
            customParamsTitle: {vi: "Các thông số tuỳ chỉnh", en: "Customizable Parameters"},
            recipeSuggestionsTitle: {vi: "Công thức Gợi ý", en: "Recipe Suggestions"},
            cl_base: {vi: "Nền", en: "Base"},
            cl_recipe_cinematic_name: {vi: "Dáng vẻ Điện ảnh", en: "Cinematic Look"},
            cl_recipe_cinematic_desc: {vi: "Giảm tương phản và độ nét để tạo cảm giác mềm mại, điện ảnh.", en: "Reduces contrast and sharpness for a soft, cinematic feel."},
            cl_recipe_vibrant_name: {vi: "Phong cảnh Rực rỡ", en: "Vibrant Landscape"},
            cl_recipe_vibrant_desc: {vi: "Tăng cường màu sắc và độ trong để cảnh vật thêm sống động.", en: "Enhances color and clarity to make landscapes more vivid."},
            cl_recipe_soft_portrait_name: {vi: "Chân dung Mềm mại", en: "Soft Portrait"},
            cl_recipe_soft_portrait_desc: {vi: "Làm dịu da và giảm tương phản để có một bức chân dung nịnh mắt.", en: "Softens skin and reduces contrast for a flattering portrait."},
            cl_recipe_teal_orange_name: {vi: "Hoài niệm Xanh & Cam", en: "Teal & Orange Nostalgia"},
            cl_recipe_teal_orange_desc: {vi: "Tạo phong cách điện ảnh hiện đại với tông màu xanh ở vùng tối và cam ở vùng sáng.", en: "Creates a modern cinematic style with teal tones in the shadows and orange in the highlights."},
            cl_recipe_dramatic_mono_name: {vi: "Kịch tính Đơn sắc", en: "Dramatic Monochrome"},
            cl_recipe_dramatic_mono_desc: {vi: "Ảnh đen trắng tương phản cao, vùng tối sâu, phù hợp kiến trúc và đường phố.", en: "High-contrast B&W with deep shadows, great for architecture and street."},
            cl_recipe_golden_hour_name: {vi: "Ánh nắng Mật ong", en: "Golden Hour Glow"},
            cl_recipe_golden_hour_desc: {vi: "Tông màu ấm, mềm mại, tái tạo ánh sáng vàng óng của giờ vàng.", en: "A warm, soft tone that recreates the golden light of the magic hour."},
            cl_recipe_urban_cool_name: {vi: "Đô thị Lạnh lùng", en: "Urban Cool"},
            cl_recipe_urban_cool_desc: {vi: "Màu lạnh, hơi giảm bão hoà, mang lại vẻ đẹp hiện đại, sạch sẽ cho cảnh thành phố.", en: "A cool, slightly desaturated look that brings a modern, clean feel to city scenes."},
            cl_recipe_vibrant_summer_name: {vi: "Mùa hè Rực rỡ", en: "Vibrant Summer"},
            cl_recipe_vibrant_summer_desc: {vi: "Tăng cường độ bão hoà của các màu nóng, tạo cảm giác năng động, tươi vui của mùa hè.", en: "Boosts the saturation of warm colors for an energetic, joyful summer vibe."},
            cl_ST_name: {vi: "ST: Tiêu chuẩn", en:"ST: Standard"},
            cl_ST_desc: {vi: "Màu tiêu chuẩn cho đa dạng chủ thể và bối cảnh.", en:"The standard finish for a wide range of subjects and scenes."},
            cl_PT_name: {vi: "PT: Chân dung", en:"PT: Portrait"},
            cl_PT_desc: {vi: "Tái tạo tông màu da mềm mại, lý tưởng cho chụp chân dung.", en:"For capturing skin in a soft tone, ideally suited for shooting portraits."},
            cl_NT_name: {vi: "NT: Trung tính", en:"NT: Neutral"},
            cl_NT_desc: {vi: "Độ bão hòa và sắc nét thấp hơn, phù hợp cho ảnh cần hậu kỳ.", en:"Lower saturation and sharpness for shooting images before they are to be processed."},
            cl_VV_name: {vi: "VV: Rực rỡ", en:"VV: Vivid"},
            cl_VV_desc: {vi: "Tăng cường độ bão hòa và tương phản để tạo ấn tượng mạnh.", en:"Saturation and contrast are heightened for a striking impression of colorful scenes and subjects."},
            cl_VV2_name: {vi: "VV2: Rực rỡ 2", en:"VV2: Vivid 2"},
            cl_VV2_desc: {vi: "Tạo ra ảnh trong và sáng với màu sắc sống động. Hiệu quả với chủ thể nhiều màu sắc.", en:"Creates a highly clear image with bright and vibrant colours. Effective for colourful subjects."},
            cl_FL_name: {vi: "FL: Giả lập phim", en:"FL: Film-like"},
            cl_FL_desc: {vi: "Tạo cảm giác như phim điện ảnh với màu sắc điềm tĩnh và bầu trời ấn tượng.", en:"For a film-like expression with calm colours and a stunning sky."},
            cl_IN_name: {vi: "IN: Chụp lấy ngay", en:"IN: Instant Camera"},
            cl_IN_desc: {vi: "Tạo cảm giác hoài cổ như ảnh chụp từ máy ảnh lấy liền.", en:"For a nostalgic expression like photos from an instant camera."},
            cl_SH_name: {vi: "SH: Soft High-key", en:"SH: Soft High-key"},
            cl_SH_desc: {vi: "Tạo không khí trong trẻo, tươi sáng, mềm mại và nhẹ nhàng.", en:"For creating a bright, transparent, soft, and gentle atmosphere."},
            cl_BW_name: {vi: "BW: Đen trắng", en:"BW: Black & White"},
            cl_BW_desc: {vi: "Tạo ảnh đơn sắc không bao giờ lỗi thời.", en:"For creating a timeless Black & White image."},
            cl_SE_name: {vi: "SE: Nâu đỏ", en:"SE: Sepia"},
            cl_SE_desc: {vi: "Tạo ảnh màu nâu đỏ cổ điển.", en:"For creating an archaic Sepia image."},
            cl_param_contrast: {vi: "Tương phản (Contrast)", en: "Contrast"},
            cl_param_contrast_desc: {vi: "Giá trị càng cao, sự khác biệt giữa vùng sáng và tối càng được nhấn mạnh.", en:"The higher the value, the more the difference between light and dark is emphasized."},
            cl_param_highlights: {vi: "Vùng sáng (Highlights)", en: "Highlights"},
            cl_param_highlights_desc: {vi: "Điều chỉnh độ sáng của các vùng sáng.", en:"Adjusts the brightness of the bright areas."},
            cl_param_shadows: {vi: "Vùng tối (Shadows)", en: "Shadows"},
            cl_param_shadows_desc: {vi: "Điều chỉnh độ tối của các vùng tối.", en:"Adjusts the darkness of the dark areas."},
            cl_param_fading: {vi: "Độ bạc màu (Fading)", en: "Fading"},
            cl_param_fading_desc: {vi: "Giá trị càng cao, hiệu ứng bạc màu càng rõ rệt.", en:"The higher the value, the more the faded-out effect is applied."},
            cl_param_saturation: {vi: "Bão hòa (Saturation)", en: "Saturation"},
            cl_param_saturation_desc: {vi: "Giá trị càng cao, màu sắc càng sống động.", en:"The higher the value, the more vivid the colours."},
            cl_param_sharpness: {vi: "Độ nét (Sharpness)", en: "Sharpness"},
            cl_param_sharpness_desc: {vi: "Điều chỉnh đường viền. Giá trị càng cao, đường viền càng được làm nổi bật.", en:"Adjusts the outline. The higher the value, the more the outlines are accentuated."},
            cl_param_sharpness_range: {vi: "Phạm vi nét (Sharpness Range)", en: "Sharpness Range"},
            cl_param_sharpness_range_desc: {vi: "Điều chỉnh phạm vi áp dụng độ nét.", en:"Adjusts the range to which sharpness is applied."},
            cl_param_clarity: {vi: "Độ trong (Clarity)", en: "Clarity"},
            cl_param_clarity_desc: {vi: "Giá trị càng cao, độ trong của ảnh càng được tăng cường.", en:"The higher the value, the more the clarity is enhanced."},
            
            explainHeader: {vi: "Làm Chủ Màu Sắc Cùng Sony Alpha", en:"Mastering Color with Sony Alpha"},
            explainSubtitle: {vi: "Hướng dẫn toàn diện để tạo ra màu sắc đậm chất riêng cho ảnh tĩnh", en:"A comprehensive guide to creating your unique color signature for stills"},
            pillarsTitle: {vi: "Hai Trụ Cột Sáng Tạo Màu Sắc", en:"The Two Pillars of Color Creation"},
            wbPillarTitle: {vi: "Trụ cột 1: White Balance - Nền Tảng Cảm Xúc", en:"Pillar 1: White Balance - The Emotional Foundation"},
            ppPillarTitle: {vi: "Trụ cột 2: Picture Profile - Tạo Dáng Vẻ Phim Ảnh", en:"Pillar 2: Picture Profile - Crafting the Film Look"},
            wbKelvinTitle: {vi: "Nhiệt Độ Kelvin (K): Tạo Tông Màu Chủ Đạo", en: "Kelvin Temperature (K): Creating the Main Tone"},
            wbKelvinDesc: {vi: 'Sử dụng thang đo Kelvin như một nét cọ lớn để "nhuộm" toàn bộ khung hình bằng tông màu ấm hoặc lạnh, định hình "mood" cho bức ảnh.', en: 'Use the Kelvin scale like a broad brush to "tint" the entire frame with warm or cool tones, shaping the photo\'s mood.'},
            wbShiftTitle: {vi: "Lưới Tinh Chỉnh (A-B/G-M Shift): Thêm Sắc Thái Tinh Vi", en:"Fine-Tuning Grid (A-B/G-M Shift): Adding Subtle Hues"},
            wbShiftDesc: {vi: 'Nếu Kelvin là nét cọ lớn, lưới tinh chỉnh là cọ tỉa. Đây là chìa khóa để mô phỏng các loại phim đặc trưng bằng cách thêm các sắc thái Hổ phách/Xanh hoặc Xanh lá/Tím.', en: 'If Kelvin is the broad brush, this is the fine-detail brush. It\'s key to simulating specific films by adding Amber/Blue or Green/Magenta tints.'},
            ppInfographicTitle: {vi: "Quy trình Tinh chỉnh Picture Profile", en:"Picture Profile Adjustment Workflow"},
            ppInfographicDesc: {vi: "Làm theo các bước sau để thiết lập Picture Profile từ đầu, cho phép bạn kiểm soát hoàn toàn giao diện cuối cùng của hình ảnh.", en:"Follow these steps to set up a Picture Profile from scratch, giving you full control over the final look of your image."},
            ppItemBlackLevel: {vi: "Black Level (Mức độ đen)", en: "Black Level"},
            ppItemBlackLevelDesc: {vi: "Thiết lập điểm đen (vùng tối nhất). Tăng (+) để nâng vùng tối (tạo look 'faded' hoài cổ), giảm (-) để vùng tối sâu hơn (tăng tương phản).", en: "Sets the black point. Increase (+) to lift shadows (for a 'faded' look), decrease (-) for deeper blacks (more contrast)."},
            ppItemGamma: {vi: "Gamma", en: "Gamma"},
            ppItemGammaDesc: {vi: "Thiết lập đường cong tương phản (contrast curve). Đây là nền tảng cho 'look' của bạn. Still & Movie cho độ tương phản cao, trong khi các gamma Cine/S-Log cho dải nhạy sáng rộng hơn.", en: "Sets the contrast curve. This is the foundation of your look. Still & Movie are punchy, while Cine/S-Log gammas offer wider dynamic range."},
            ppItemBlackGamma: {vi: "Black Gamma", en: "Black Gamma"},
            ppItemBlackGammaDesc: {vi: "Tinh chỉnh đường cong tương phản ở vùng tối. 'Wide' ảnh hưởng vùng rộng hơn, 'Narrow' ảnh hưởng vùng hẹp hơn.", en: "Fine-tunes the contrast curve in the shadow areas. 'Wide' affects a broader range, 'Narrow' affects a smaller range."},
            ppItemKnee: {vi: "Knee (Điểm uốn)", en: "Knee"},
            ppItemKneeDesc: {vi: "Kiểm soát độ nén ở vùng sáng (highlight) để tránh bị 'cháy'. Chế độ tự động (Auto) hoạt động tốt, chế độ thủ công (Manual) cho phép kiểm soát chính xác hơn.", en: "Controls highlight compression to prevent 'clipping'. Auto mode works well; Manual mode gives precise control."},
            ppItemColorMode: {vi: "Color Mode (Chế độ màu)", en: "Color Mode"},
            ppItemColorModeDesc: {vi: "Xác định cách màu sắc được tái tạo. Nên chọn chế độ phù hợp với Gamma đã chọn (ví dụ: Cine4 với Pro/Cinema, S-Log3 với S-Gamut3.Cine).", en: "Determines how colors are reproduced. Should be matched with the chosen Gamma (e.g., Cine4 with Pro/Cinema, S-Log3 with S-Gamut3.Cine)."},
            ppItemSaturation: {vi: "Saturation (Bão hòa)", en: "Saturation"},
            ppItemSaturationDesc: {vi: "Điều chỉnh độ đậm/nhạt tổng thể của tất cả các màu.", en: "Adjusts the overall intensity of all colors."},
            ppItemColorPhase: {vi: "Color Phase (Pha màu)", en: "Color Phase"},
            ppItemColorPhaseDesc: {vi: "Xoay trục màu sắc tổng thể. Hữu ích để tinh chỉnh nhẹ toàn bộ tông màu mà không ảnh hưởng đến từng màu riêng lẻ.", en: "Shifts the overall hue of all colors. Useful for subtle, global color tone adjustments without affecting individual colors."},
            ppItemColorDepth: {vi: "Color Depth (Độ sâu màu)", en: "Color Depth"},
            ppItemColorDepthDesc: {vi: "Công cụ mạnh mẽ nhất. Tăng/giảm độ sáng của từng kênh màu riêng lẻ (Đỏ, Lục, Lam, Lục lam, Tím, Vàng).", en: "The most powerful tool. Increases/decreases the brightness of individual color channels (R, G, B, C, M, Y)."},
            ppItemDetail: {vi: "Detail (Chi tiết)", en: "Detail"},
            ppItemDetailDesc: {vi: "Kiểm soát độ sắc nét. Để có 'look' phim mềm mại, hãy giảm mạnh (ví dụ: -7).", en: "Controls the sharpening. For a soft, filmic look, decrease it significantly (e.g., -7)."},
            recallTitle: { vi: 'Lưu Trữ & Tái Sử Dụng: Làm Chủ Memory Recall', en: 'Save & Reuse: Mastering Memory Recall' },
            recallDesc: { vi: 'Đừng lãng phí công sức! Lưu lại các công thức của bạn vào bộ nhớ của máy ảnh để gọi ra nhanh chóng chỉ bằng một thao tác xoay nút.', en: 'Don\'t waste your effort! Save your recipes to the camera\'s memory for quick recall with a simple turn of a dial.' },
            recallInternalTitle: { vi: 'Bộ Nhớ Trong (1, 2, 3)', en: 'Internal Memory (1, 2, 3)' },
            recallInternalDesc: { vi: 'Lưu trực tiếp vào máy. Truy cập nhanh nhất bằng cách xoay vòng xoay chế độ. Lý tưởng cho các công thức bạn sử dụng hàng ngày.', en: 'Saves directly to the camera. Quickest access via the mode dial. Ideal for your daily-use recipes.' },
            recallCardTitle: { vi: 'Thẻ Nhớ (M1, M2, M3, M4)', en: 'Memory Card (M1, M2, M3, M4)' },
            recallCardDesc: { vi: 'Lưu dưới dạng file trên thẻ nhớ. Cực kỳ hữu ích để sao lưu an toàn hoặc chuyển công thức sang một thân máy Sony khác.', en: 'Saves as a file on your memory card. Extremely useful for backups or transferring recipes to another Sony camera body.' },
            tutorialTitle: { vi: "Hướng dẫn Cài đặt Nhanh", en: "Quick Setup Guide" },
            tutorialStep1Title: { vi: "Bước 1: Tìm Picture Profile", en: "Step 1: Find Picture Profile" },
            tutorialStep1P1: { vi: "<strong>Máy ảnh đời mới:</strong> Menu → Exposure/Color (biểu tượng máy ảnh) → Color/Tone → Picture Profile.", en: "<strong>Newer Cameras:</strong> Menu → Exposure/Color (camera icon) → Color/Tone → Picture Profile." },
            tutorialStep1P2: { vi: "<strong>Máy ảnh đời cũ:</strong> Menu → Color/WB/Img. Processing (biểu tượng bảng màu) → Picture Profile.", en: "<strong>Older Cameras:</strong> Menu → Color/WB/Img. Processing (palette icon) → Picture Profile." },
            tutorialStep2Title: { vi: "Bước 2: Chọn và Reset", en: "Step 2: Select & Reset" },
            tutorialStep2P1: { vi: "Chọn một profile trống (ví dụ: PP10), đi vào trong và nhấn nút 'Xoá' để reset về mặc định.", en: "Choose an empty profile (e.g., PP10), enter it, and press the 'Delete' button to reset it to default." },
            tutorialStep3Title: { vi: "Bước 3: Nhập thông số", en: "Step 3: Enter Parameters" },
            tutorialStep3P1: { vi: "Cẩn thận nhập tất cả các thông số của công thức, từ Black Level đến Detail.", en: "Carefully enter all parameters from the recipe, from Black Level to Detail." },
            tutorialStep4Title: { vi: "Bước 4: Cài đặt White Balance", en: "Step 4: Set White Balance" },
            tutorialStep4P1: { vi: "Thoát khỏi Picture Profile, vào mục <strong>White Balance</strong> và chỉnh theo nhiệt độ K và WB Shift (Color Filter) được ghi trong công thức.", en: "Exit Picture Profile, go to <strong>White Balance</strong>, and adjust the Kelvin temperature and WB Shift (Color Filter) as specified in the recipe." },
            exposureNoteTitle: { vi: "Lưu ý về Phơi sáng", en: "Note on Exposure" },
            exposureNoteDesc: { vi: "Hầu hết các công thức được tối ưu khi chụp ở mức phơi sáng 0EV với chế độ đo sáng 'Toàn màn hình trung bình' (Entire Screen Avg.). Các công thức dựa trên S-Log có thể cần tăng phơi sáng (overexpose) để có kết quả tốt nhất.", en: "Most recipes are optimized for 0EV exposure with 'Entire Screen Avg.' metering mode. Recipes based on S-Log may require overexposure for best results." },

            // Quiz Questions
            quizQ1: {vi: "Gu thẩm mỹ của bạn?", en: "Your aesthetic?"},   
            quizQ1A1: {vi: "Cổ điển", en: "Classic"},   
            quizQ1A2: {vi: "Hiện đại", en: "Modern"},   
            quizQ1A3: {vi: "Điện ảnh", en: "Cinematic"},   
            quizQ1A4: {vi: "Nghệ thuật", en: "Artistic"},
            quizQ2: {vi: "Kế hoạch chụp hôm nay?", en: "Today's shoot plan?"},   
            quizQ2A1: {vi: "Chân dung", en: "Portraits"},   
            quizQ2A2: {vi: "Phong cảnh", en: "Landscapes"},   
            quizQ2A3: {vi: "Đường phố", en: "Street"},   
            quizQ2A4: {vi: "Đời thường", en: "Everyday"},
            quizQ3: {vi: "Tâm trạng lúc này?", en: "Current mood?"},   
            quizQ3A1: {vi: "Vui vẻ", en: "Happy"},   
            quizQ3A2: {vi: "Trầm tư", en: "Contemplative"},   
            quizQ3A3: {vi: "Năng động", en: "Dynamic"},   
            quizQ3A4: {vi: "Bình yên", en: "Peaceful"},
            quizQ4: {vi: "Bạn thích du lịch đến đâu?", en: "Where do you like to travel?"},
            quizQ4A1: {vi: "Biển xanh", en: "Beaches"},
            quizQ4A2: {vi: "Núi rừng", en: "Mountains"},
            quizQ4A3: {vi: "Thành phố đô thị", en: "Urban Cities"},
            quizQ4A4: {vi: "Phố cổ", en: "Old Towns"},
            quizQ5: {vi: "Bạn thích tone màu nào?", en: "Which color tone do you prefer?"},
            quizQ5A1: {vi: "Tone ấm", en: "Warm Tones"},
            quizQ5A2: {vi: "Tone lạnh", en: "Cool Tones"},
            quizQ5A3: {vi: "Trung tính", en: "Neutral"},
            quizQ6: {vi: "Xu hướng hình ảnh của bạn là gì?", en: "What is your image trend?"},
            quizQ6A1: {vi: "Hơi thở Á Đông", en: "Eastern Vibe"},
            quizQ6A2: {vi: "Cảm hứng Phương Tây", en: "Western Inspiration"},
            quizQ7: {vi: "Bạn thích độ tương phản ra sao?", en: "How do you like the contrast?"},
            quizQ7A1: {vi: "Cao (Gắt)", en: "High (Punchy)"},
            quizQ7A2: {vi: "Thấp (Mềm mại)", en: "Low (Soft)"},
            quizQ7A3: {vi: "Trung bình", en: "Medium"},
            quizQ8: {vi: "Bạn thích độ bão hòa màu sắc như thế nào?", en: "How do you like your color saturation?"},
            quizQ8A1: {vi: "Cao (Rực rỡ)", en: "High (Vibrant)"},
            quizQ8A2: {vi: "Thấp (Nhẹ nhàng)", en: "Low (Subtle)"},
            quizQ8A3: {vi: "Trung bình", en: "Medium"},
        };
