// recipes-data.js
// File này chứa toàn bộ dữ liệu về các công thức màu của Alpha AI Color Lab.
// Việc tách riêng file dữ liệu giúp mã nguồn chính (index.html) gọn gàng và dễ quản lý hơn.

const recipesData = [
   {
        "id": "vektro-100",
        "name": { "vi": "1. Chiều Tàn", "en": "1. Vektro 100" },
        "description": { "vi": "Tái tạo sắc cam rực của lửa và vùng tối sâu thẳm.", "en": "Vibrant orange of fire and deep shadows." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "4000K, A5-M0.5",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 92.5% +5", "Color Mode": "S-Gamut3.Cine", "Saturation": "+27", "Color Phase": "+6" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "+5", "C": "+5", "M": "+2", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#E57373", "coords": { "x": 7.8, "y": 8.1 }
    },
    {
        "id": "senova-light",
        "name": { "vi": "2. Đà Lạt trong sương", "en": "2. Senova Light" },
        "description": { "vi": "Màu lam lạnh và tương phản cao, gợi cảm giác mờ ảo.", "en": "Cool blue tone with high contrast, evoking a misty feeling." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "8000K, B2-M2",
        "notes": { "vi": "Chế độ ban đêm: 2900K, A5-G1", "en": "Nighttime: 2900K, A5-G1" },
        "settings": { "Black level": "-15", "Gamma": "Cine3", "Black Gamma": "Wide +7", "Knee": "Manual 85% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+20", "Color Phase": "+7" },
        "colorDepth": { "R": "-5", "G": "-1", "B": "+3", "C": "+4", "M": "+5", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#64B5F6", "coords": { "x": 8.5, "y": 1.2 }
    },
    {
        "id": "fuji-400h",
        "name": { "vi": "3. Đồng Cỏ Mộc Châu", "en": "3. Fuji 400H" },
        "description": { "vi": "Tôn vinh sắc xanh tươi mát của cỏ cây dưới nắng hạ.", "en": "Honors the fresh green tones of plants under the summer sun." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "3700K, A7-M0.5",
        "settings": { "Black level": "0", "Gamma": "Movie", "Black Gamma": "Wide +7", "Knee": "Manual 80% +4", "Color Mode": "Still", "Saturation": "+11", "Color Phase": "-3" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "-3", "C": "-3", "M": "-5", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#81C784", "coords": { "x": -7.1, "y": -8.2 }
    },
    {
        "id": "evpro-plus",
        "name": { "vi": "4. Đông Dương", "en": "4. EvPro+" },
        "description": { "vi": "Màu vàng rực rỡ và bão hòa cao, nắm bắt năng lượng.", "en": "Vibrant yellow, high saturation, captures energy." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "4300K, A3.5",
        "settings": { "Black level": "-10", "Gamma": "Cine1", "Black Gamma": "Middle +7", "Knee": "Auto", "Color Mode": "S-Gamut3.Cine", "Saturation": "+32", "Color Phase": "+5" },
        "colorDepth": { "R": "-3", "G": "+4", "B": "+3", "C": "+3", "M": "-2", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFD54F", "coords": { "x": 7.2, "y": 7.5 }
    },
    {
        "id": "ektar-100",
        "name": { "vi": "5. Hoàng Hôn Sài Gòn", "en": "5. Ektar 100" },
        "description": { "vi": "Sắc đỏ và cam đậm, bão hòa cao, tái hiện hoàng hôn.", "en": "Rich red and orange hues, high saturation, recreating sunsets." },
        "type": "color", "contrast": "low", "saturation": "high",
        "whiteBalance": "5000K, A2-M1",
        "settings": { "Black level": "+6", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+25", "Color Phase": "+2" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "+5", "C": "+5", "M": "+5", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FF8A65", "coords": { "x": -8.3, "y": 8.8 }
    },
    {
        "id": "kodak-gold-v1",
        "name": { "vi": "6. Ký Ức Vàng Son", "en": "6. Kodak Gold" },
        "description": { "vi": "Ánh vàng ấm áp đặc trưng, gợi nhớ thập niên 90.", "en": "A distinctive warm golden glow, reminiscent of the 90s." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "8500K, B3-M1.75",
        "settings": { "Black level": "-5", "Gamma": "Movie", "Black Gamma": "Wide +7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3/S-Gamut", "Saturation": "+32", "Color Phase": "+6" },
        "colorDepth": { "R": "-2", "G": "0", "B": "+5", "C": "+5", "M": "0", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFB74D", "coords": { "x": -0.5, "y": 7.9 }
    },
    {
        "id": "kodak-gold-200-v2",
        "name": { "vi": "7. Hoàng Kim V2", "en": "7. Kodak Gold 200 V2" },
        "description": { "vi": "Một phiên bản khác của Kodak Gold với tông màu ấm và độ bão hòa cao.", "en": "Another version of Kodak Gold with warm tones and high saturation." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "4600K, A7-G1.25",
        "settings": { "Black level": "+2", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+25", "Color Phase": "+5" },
        "colorDepth": { "R": "+3", "G": "-3", "B": "-5", "C": "-3", "M": "+3", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFC107", "coords": { "x": -1.5, "y": 8.2 }
    },
    {
        "id": "kodak-portra-800",
        "name": { "vi": "8. Chân dung mùa thu", "en": "8. Kodak Portra 800" },
        "description": { "vi": "Màu sắc ấm áp, lý tưởng cho chụp chân dung trong điều kiện ánh sáng yếu.", "en": "Warm colors, ideal for portraits in low light conditions." },
        "type": "color", "contrast": "medium", "saturation": "medium",
        "whiteBalance": "4500K, A7-M1",
        "notes": { "vi": "Tắt Gamma Assist!", "en": "Turn Off Gamma Assist!" },
        "settings": { "Black level": "-15", "Gamma": "S-Log2/S-Log3", "Black Gamma": "Middle -7", "Knee": "Manual 75% +5", "Color Mode": "Still", "Saturation": "+20", "Color Phase": "+3" },
        "colorDepth": { "R": "+3", "G": "+5", "B": "+5", "C": "+7", "M": "+7", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#D7CCC8", "coords": { "x": -2.2, "y": 6.5 }
    },
    {
        "id": "kodak-portra-400-v1",
        "name": { "vi": "9. Chân dung cổ điển", "en": "9. Kodak Portra 400 V1" },
        "description": { "vi": "Tông màu da tự nhiên và độ bão hòa dịu nhẹ, một lựa chọn kinh điển.", "en": "Natural skin tones and mild saturation, a classic choice." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "3900K, A7-M0.75",
        "settings": { "Black level": "+4", "Gamma": "Movie", "Black Gamma": "Narrow -7", "Knee": "Manual 80% +4", "Color Mode": "Still", "Saturation": "+14", "Color Phase": "-2" },
        "colorDepth": { "R": "-3", "G": "+5", "B": "-3", "C": "-3", "M": "-5", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#A1887F", "coords": { "x": -8.1, "y": 4.5 }
    },
    {
        "id": "kodak-portra-400-v2",
        "name": { "vi": "10. Ngọc Bích", "en": "10. Kodak Portra 400 V2" },
        "description": { "vi": "Tông màu dịu mát với sắc xanh ngọc bích nổi bật.", "en": "A cool tone with prominent jade green hues." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "3600K, A7-G1",
        "settings": { "Black level": "+11", "Gamma": "Movie", "Black Gamma": "Narrow -7", "Knee": "Manual 85% +4", "Color Mode": "Still", "Saturation": "+11", "Color Phase": "-4" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-3", "C": "+2", "M": "+5", "Y": "+2" },
        "detailSettings": { "Level": "-7", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 5", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#4DB6AC", "coords": { "x": -8.8, "y": -7.2 }
    },
    {
        "id": "kodak-portra-160",
        "name": { "vi": "11. Chân dung ánh sáng ngày", "en": "11. Kodak Portra 160" },
        "description": { "vi": "Màu sắc tinh tế và hạt mịn, hoàn hảo cho chụp chân dung ngoài trời.", "en": "Subtle colors and fine grain, perfect for outdoor portraits." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "4200K, A7-M1",
        "settings": { "Black level": "-10", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+7", "Color Phase": "+3" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-3", "C": "-3", "M": "-5", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BCAAA4", "coords": { "x": -7.5, "y": -4.8 }
    },
    {
        "id": "kodak-color-plus-200",
        "name": { "vi": "12. Sắc màu ký ức", "en": "12. Kodak Color Plus 200" },
        "description": { "vi": "Tông màu ấm áp và hoài cổ, gợi nhớ những cuộn phim xưa.", "en": "A warm and nostalgic tone, reminiscent of old film rolls." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "4000K, A7-G1",
        "settings": { "Black level": "+2", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 75% +5", "Color Mode": "S-Gamut3", "Saturation": "+32", "Color Phase": "+4" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+7", "C": "+7", "M": "+7", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFB74D", "coords": { "x": 2.5, "y": 8.5 }
    },
    {
        "id": "kodak-ultra-max-400",
        "name": { "vi": "13. Tối đa sắc màu", "en": "13. Kodak Ultra Max 400" },
        "description": { "vi": "Độ bão hòa cao và màu sắc sống động cho những bức ảnh đầy năng lượng.", "en": "High saturation and vivid colors for energetic photos." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "4500K, A7-M0.75",
        "settings": { "Black level": "+2", "Gamma": "Movie", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+8", "Color Phase": "-1" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "-3", "C": "-5", "M": "+5", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#EF5350", "coords": { "x": 1.0, "y": 7.0 }
    },
    {
        "id": "ektachrome",
        "name": { "vi": "14. Sắc màu dương bản", "en": "14. EktaChrome" },
        "description": { "vi": "Màu sắc trong trẻo và sạch sẽ, đặc trưng của dòng phim dương bản.", "en": "Clean and clear colors, characteristic of slide films." },
        "type": "color", "contrast": "medium", "saturation": "medium",
        "whiteBalance": "3600K, A7-M1",
        "settings": { "Black level": "-4", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Manual 80% +4", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-1" },
        "colorDepth": { "R": "+3", "G": "+5", "B": "-4", "C": "+2", "M": "+6", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#4FC3F7", "coords": { "x": 2.8, "y": -3.5 }
    },
    {
        "id": "kodachrome-v1",
        "name": { "vi": "15. Huyền thoại Kodachrome", "en": "15. Kodachrome V1" },
        "description": { "vi": "Tái tạo tông màu độc đáo của dòng phim Kodachrome huyền thoại.", "en": "Recreates the unique color tones of the legendary Kodachrome film." },
        "type": "color", "contrast": "medium", "saturation": "medium",
        "whiteBalance": "4200K, A7-M0.5",
        "settings": { "Black level": "+8", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+12", "Color Phase": "-2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+4", "C": "+4", "M": "+5", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#F44336", "coords": { "x": 3.3, "y": 6.1 }
    },
    {
        "id": "kodachrome-v2",
        "name": { "vi": "16. Kodachrome V2", "en": "16. Kodachrome V2" },
        "description": { "vi": "Một biến thể khác của Kodachrome với tông màu ấm và tương phản nhẹ.", "en": "Another variation of Kodachrome with warm tones and soft contrast." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "4500K, A7-M0.5",
        "settings": { "Black level": "-10", "Gamma": "Cine1", "Black Gamma": "Middle +7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+17", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "+6", "B": "+2", "C": "+7", "M": "+7", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#D32F2F", "coords": { "x": 7.0, "y": 6.8 }
    },
    {
        "id": "kodachrome-v3",
        "name": { "vi": "17. Kodachrome V3", "en": "17. Kodachrome V3" },
        "description": { "vi": "Tông màu xanh và đỏ được nhấn mạnh, tạo cảm giác cổ điển.", "en": "Emphasized blue and red tones, creating a classic feel." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "4700K, A7-G0.5",
        "settings": { "Black level": "-15", "Gamma": "Cine1", "Black Gamma": "Wide -7", "Knee": "Manual 82.5% +4", "Color Mode": "S-Cinetone/Still", "Saturation": "+10", "Color Phase": "+2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "-7", "C": "-6", "M": "+3", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#C62828", "coords": { "x": 7.4, "y": 5.2 }
    },
    {
        "id": "kodachrome-v4",
        "name": { "vi": "18. Kodachrome V4", "en": "18. Kodachrome V4" },
        "description": { "vi": "Phiên bản Kodachrome với tông màu xanh da trời nổi bật và cân bằng trắng ấm.", "en": "A Kodachrome version with prominent sky blue tones and warm white balance." },
        "type": "color", "contrast": "medium", "saturation": "medium",
        "whiteBalance": "4000K, A7-M2",
        "settings": { "Black level": "+6", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+14", "Color Phase": "-3" },
        "colorDepth": { "R": "0", "G": "+7", "B": "+5", "C": "-2", "M": "+3", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#B71C1C", "coords": { "x": 3.8, "y": 5.9 }
    },
    {
        "id": "leicachrome",
        "name": { "vi": "19. Màu Leica", "en": "19. Leicachrome" },
        "description": { "vi": "Lấy cảm hứng từ màu sắc đặc trưng của máy ảnh Leica, với tông màu ấm và dễ chịu.", "en": "Inspired by the characteristic colors of Leica cameras, with warm and pleasant tones." },
        "type": "color", "contrast": "medium", "saturation": "low",
        "whiteBalance": "7000K, B5-M0.25",
        "settings": { "Black level": "-9", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+6", "Color Phase": "+2" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+3", "C": "-5", "M": "+3", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#8D6E63", "coords": { "x": 1.5, "y": 2.5 }
    },
    {
        "id": "fuji-provia",
        "name": { "vi": "20. Fuji Provia", "en": "20. Fuji Provia" },
        "description": { "vi": "Tái tạo màu sắc trung thực và sống động của phim Fuji Provia.", "en": "Recreates the true and vivid colors of Fuji Provia film." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "4000K, A7-M0.25",
        "settings": { "Black level": "+2", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+2", "Color Phase": "+1" },
        "colorDepth": { "R": "+1", "G": "+7", "B": "0", "C": "+3", "M": "+2", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#81C784", "coords": { "x": -6.5, "y": -7.0 }
    },
    {
        "id": "provia-rx",
        "name": { "vi": "21. Provia RX", "en": "21. Provia RX" },
        "description": { "vi": "Một biến thể của Provia với độ tương phản cao hơn và màu sắc mạnh mẽ hơn.", "en": "A variation of Provia with higher contrast and stronger colors." },
        "type": "color", "contrast": "high", "saturation": "low",
        "whiteBalance": "4000K, A6.5-M1.75",
        "settings": { "Black level": "-10", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Manual 80% +3", "Color Mode": "Still", "Saturation": "+5", "Color Phase": "-2" },
        "colorDepth": { "R": "-2", "G": "+7", "B": "+7", "C": "+5", "M": "+3", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#689F38", "coords": { "x": 7.2, "y": -6.8 }
    },
    {
        "id": "velvia-pro",
        "name": { "vi": "22. Velvia Pro", "en": "22. Velvia Pro" },
        "description": { "vi": "Độ bão hòa màu cao, đặc biệt là màu xanh lá và xanh dương, lý tưởng cho phong cảnh.", "en": "High color saturation, especially greens and blues, ideal for landscapes." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "3900K, A7-M0.25",
        "settings": { "Black level": "-8", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-1" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+1", "C": "+2", "M": "-7", "Y": "0" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#388E3C", "coords": { "x": 2.0, "y": -5.0 }
    },
    {
        "id": "astia",
        "name": { "vi": "23. Astia", "en": "23. Astia" },
        "description": { "vi": "Tông màu mềm mại và tông da đẹp, phù hợp cho chụp ảnh thời trang và chân dung.", "en": "Soft tones and beautiful skin tones, suitable for fashion and portraits." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "4100K, A7-M0.25",
        "settings": { "Black level": "-8", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+5", "Color Phase": "0" },
        "colorDepth": { "R": "0", "G": "+2", "B": "+3", "C": "+2", "M": "-7", "Y": "0" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFE0B2", "coords": { "x": -5.8, "y": -3.2 }
    },
    {
        "id": "pro-neg-std",
        "name": { "vi": "24. Pro Neg Std", "en": "24. Pro Neg Std" },
        "description": { "vi": "Tông màu trung tính, độ tương phản thấp, lý tưởng cho việc hậu kỳ.", "en": "Neutral tones, low contrast, ideal for post-processing." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "3900K, A7",
        "settings": { "Black level": "+2", "Gamma": "Still", "Black Gamma": "Wide -5", "Knee": "Manual 75% +3", "Color Mode": "Still", "Saturation": "-6", "Color Phase": "+1" },
        "colorDepth": { "R": "-2", "G": "+7", "B": "+3", "C": "-5", "M": "-4", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#CFD8DC", "coords": { "x": -7.3, "y": -8.8 }
    },
    {
        "id": "reala-ace",
        "name": { "vi": "25. Reala Ace", "en": "25. Reala Ace" },
        "description": { "vi": "Tái tạo màu sắc chân thực với độ bão hòa vừa phải.", "en": "Reproduces true-to-life colors with moderate saturation." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "3900K, A7",
        "settings": { "Black level": "+2", "Gamma": "Still", "Black Gamma": "Wide +2", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-1" },
        "colorDepth": { "R": "-2", "G": "+7", "B": "+4", "C": "+2", "M": "-4", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BDBDBD", "coords": { "x": -4.5, "y": 3.5 }
    },
    {
        "id": "sony-classic-negative",
        "name": { "vi": "26. Âm bản cổ điển Sony", "en": "26. Sony Classic Negative" },
        "description": { "vi": "Tông màu xanh lá và đỏ được xử lý đặc biệt, tạo cảm giác hoài cổ.", "en": "Specially treated green and red tones create a nostalgic feel." },
        "type": "color", "contrast": "medium", "saturation": "medium",
        "whiteBalance": "9900K, B6-M0.5",
        "settings": { "Black level": "+4", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +5", "Color Mode": "S-Cinetone/Still", "Saturation": "+5", "Color Phase": "+1" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "-4", "C": "-4", "M": "-5", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#80CBC4", "coords": { "x": 1.8, "y": -4.2 }
    },
    {
        "id": "fuji-nostalgic-neg",
        "name": { "vi": "27. Hoài niệm Fuji", "en": "27. Fuji Nostalgic Neg" },
        "description": { "vi": "Màu sắc ấm áp, vùng tối mềm mại, mang lại cảm giác của những năm 70.", "en": "Warm colors, soft shadows, bringing a 70s vibe." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "4300K, A7-M0.25",
        "settings": { "Black level": "+2", "Gamma": "Movie", "Black Gamma": "Middle +2", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+3", "Color Phase": "+1" },
        "colorDepth": { "R": "+1", "G": "+7", "B": "+2", "C": "+2", "M": "+4", "Y": "+2" },
        "detailSettings": { "Level": "-7", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "0", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFAB91", "coords": { "x": -5.2, "y": -2.1 }
    }
].concat([
    {
        "id": "classic-chrome",
        "name": { "vi": "28. Đô Thị", "en": "28. Classic Chrome" },
        "description": { "vi": "Tông màu trầm, bão hòa thấp, tương phản cao, gai góc.", "en": "Subdued tone, low saturation, high contrast for a gritty feel." },
        "type": "color", "contrast": "high", "saturation": "low",
        "whiteBalance": "4000K, A7-M0.5",
        "settings": { "Black level": "-7", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "-5", "Color Phase": "+2" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "+2", "C": "+3", "M": "-6", "Y": "-1" },
        "detailSettings": { "Level": "-7", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#78909C", "coords": { "x": 8.1, "y": -8.5 }
    },
    {
        "id": "fuji-eterna",
        "name": { "vi": "29. Điệp Vụ Melancholy", "en": "29. Fuji Eterna" },
        "description": { "vi": "Màu sắc trầm, bão hòa rất thấp, tạo cảm giác điện ảnh.", "en": "Subdued colors, very low saturation for a cinematic feel." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "4000K, A7-M0.25",
        "settings": { "Black level": "+7", "Gamma": "Movie", "Black Gamma": "Wide -5", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "-5", "Color Phase": "+1" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-2", "C": "+6", "M": "+4", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#A1887F", "coords": { "x": -9.2, "y": -9.1 }
    },
    {
        "id": "sony-eterna",
        "name": { "vi": "30. Giấc Mơ Xanh", "en": "30. Sony Eterna" },
        "description": { "vi": "Tông màu lạnh, ám xanh, bão hòa cao, siêu thực và mơ màng.", "en": "A cool, blue-tinted tone, high saturation, surreal and dreamy." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "4000K, A7-M1",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Wide -5", "Knee": "Manual 87.5% +3", "Color Mode": "S-Gamut3", "Saturation": "+32", "Color Phase": "+6" },
        "colorDepth": { "R": "-3", "G": "-2", "B": "+3", "C": "+7", "M": "-3", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#64B5F6", "coords": { "x": 8.0, "y": 9.0 }
    },
    {
        "id": "acros-x",
        "name": { "vi": "31. Than Chì", "en": "31. Acros X" },
        "description": { "vi": "Tương phản mạnh, chi tiết sắc nét, như bút than chì.", "en": "Strong contrast, sharp details, like a graphite sketch." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-11", "Gamma": "Still", "Black Gamma": "Middle -3", "Knee": "Manual 85% +5", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "+1", "B": "-1", "C": "+3", "M": "-3", "Y": "-1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#9E9E9E", "coords": { "x": 8.2, "y": -7.5 }
    },
    {
        "id": "acros-xy",
        "name": { "vi": "32. Đá Cuội", "en": "32. Acros XY" },
        "description": { "vi": "Dải tông màu xám phong phú với độ chuyển mượt mà.", "en": "Rich range of gray tones with smooth transitions." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-10", "Gamma": "Still", "Black Gamma": "Middle -3", "Knee": "Manual 85% +4", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "-4", "G": "+1", "B": "+3", "C": "+3", "M": "-4", "Y": "-1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BDBDBD", "coords": { "x": 7.1, "y": -3.1 }
    },
    {
        "id": "acros-xr",
        "name": { "vi": "33. Bóng Tối", "en": "33. Acros XR" },
        "description": { "vi": "Tăng cường độ sâu cho vùng tối, tạo cái nhìn kịch tính.", "en": "Enhances the depth of shadows for a dramatic look." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Middle +5", "Knee": "Manual 85% +5", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "-6", "G": "+1", "B": "+5", "C": "+4", "M": "-6", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#757575", "coords": { "x": 9.0, "y": 5.5 }
    },
    {
        "id": "acros-xg",
        "name": { "vi": "34. Tương Phản Gắt", "en": "34. Acros XG" },
        "description": { "vi": "Tương phản cực cao, làm nổi bật đường nét, hình khối.", "en": "Extremely high contrast, emphasizing lines and shapes." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 85% +5", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "-4", "B": "-1", "C": "+2", "M": "-1", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#616161", "coords": { "x": 9.5, "y": -8.0 }
    },
    {
        "id": "fortia-50",
        "name": { "vi": "35. Lục Lâm", "en": "35. Fortia 50" },
        "description": { "vi": "Màu xanh lá cây đậm và bão hòa, cảm giác sâu thẳm của rừng già.", "en": "Deep, saturated green, profound feeling of an ancient forest." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3500K, A7-G0.25",
        "settings": { "Black level": "-2", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +5", "Color Mode": "ITU709Matrix", "Saturation": "+18", "Color Phase": "-3" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+7", "C": "+7", "M": "+7", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#2E7D32", "coords": { "x": 7.5, "y": -7.0 }
    },
    {
        "id": "sony-nostalgic-neg",
        "name": { "vi": "36. Trà Chanh", "en": "36. Sony Nostalgic Neg" },
        "description": { "vi": "Tông màu vàng chanh và xanh lá cây nhẹ, tạo cảm giác tươi mới.", "en": "Light lemon-yellow and green tone, creating a fresh feeling." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "4500K, A7-M2",
        "settings": { "Black level": "+6", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 80% +4", "Color Mode": "Still/Pro", "Saturation": "+14", "Color Phase": "-3" },
        "colorDepth": { "R": "+2", "G": "+5", "B": "-7", "C": "+4", "M": "-6", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#CDDC39", "coords": { "x": -6.0, "y": 6.0 }
    },
    {
        "id": "classic-cinema",
        "name": { "vi": "37. Phim Cổ Điển", "en": "37. Classic Cinema" },
        "description": { "vi": "Tông màu điện ảnh, vùng tối được nâng, màu sắc ám xanh.", "en": "Cinematic tone with lifted shadows and a blue cast." },
        "type": "color", "contrast": "medium", "saturation": "low",
        "whiteBalance": "AWB White Priority, A2-G0.25",
        "settings": { "Black level": "-2", "Gamma": "Movie", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+12", "Color Phase": "-1" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-5", "C": "+5", "M": "-5", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#A1887F", "coords": { "x": -2.0, "y": -8.5 }
    },
    {
        "id": "oktar",
        "name": { "vi": "38. Màu Nhiệt Đới", "en": "38. Oktar" },
        "description": { "vi": "Bão hòa cao, màu sắc rực rỡ, đặc biệt là xanh dương và xanh lá.", "en": "High saturation, vibrant colors, especially blues and greens." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "7000K, B2-M1",
        "settings": { "Black level": "-10", "Gamma": "Movie", "Black Gamma": "Wide +7", "Knee": "Manual 75% +4", "Color Mode": "Movie", "Saturation": "+25", "Color Phase": "+2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+7", "C": "+7", "M": "+7", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#0091EA", "coords": { "x": 9.0, "y": 2.0 }
    },
    {
        "id": "zero-mute",
        "name": { "vi": "39. Xanh Trầm Lặng", "en": "39. Zero Mute" },
        "description": { "vi": "Tông màu teal trầm, bão hòa thấp, tạo cảm giác yên tĩnh.", "en": "A subdued, low-saturation teal tone, creating a quiet feel." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "7000K, B1-M1",
        "settings": { "Black level": "+7", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 80% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+10", "Color Phase": "+7" },
        "colorDepth": { "R": "0", "G": "+7", "B": "+5", "C": "+5", "M": "+5", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#4DB6AC", "coords": { "x": -8.5, "y": -2.5 }
    },
    {
        "id": "cinechrome",
        "name": { "vi": "40. Sắc Màu Điện Ảnh", "en": "40. CineChrome" },
        "description": { "vi": "Màu sắc sống động, tương phản cao, mang lại cái nhìn điện ảnh hiện đại.", "en": "Vivid colors, high contrast, providing a modern cinematic look." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3900K, A7",
        "notes": { "vi": "Tắt Gamma Assist!", "en": "Turn Off Gamma Assist!" },
        "settings": { "Black level": "-15", "Gamma": "HLG3", "Black Gamma": "Wide 0", "Knee": "Auto", "Color Mode": "BT.2020", "Saturation": "+32", "Color Phase": "+7" },
        "colorDepth": { "R": "-4", "G": "-1", "B": "+5", "C": "+4", "M": "+5", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#E91E63", "coords": { "x": 9.2, "y": 6.5 }
    },
    {
        "id": "pro-color",
        "name": { "vi": "41. Màu Chuyên Nghiệp", "en": "41. Pro Color" },
        "description": { "vi": "Màu sắc cân bằng, bão hòa tốt, cho kết quả chuyên nghiệp.", "en": "Well-balanced, saturated colors for professional results." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3900K, A7-G1.5",
        "notes": { "vi": "Tắt Gamma Assist!", "en": "Turn Off Gamma Assist!" },
        "settings": { "Black level": "-15", "Gamma": "HLG3", "Black Gamma": "Wide 0", "Knee": "Auto 90% High", "Color Mode": "Rec.709", "Saturation": "+22", "Color Phase": "+1" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+3", "C": "-4", "M": "-2", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#03A9F4", "coords": { "x": 7.0, "y": 1.0 }
    },
    {
        "id": "blue-velvet-cinestill-50d",
        "name": { "vi": "42. Nhung Xanh", "en": "42. Blue Velvet / Cinestill 50D" },
        "description": { "vi": "Tông màu xanh dương lạnh, mềm mại như nhung, sang trọng và bí ẩn.", "en": "A cool, soft blue tone like velvet, luxurious and mysterious." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "7400K, B4-M1",
        "settings": { "Black level": "0", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-3" },
        "colorDepth": { "R": "+4", "G": "+5", "B": "-4", "C": "-4", "M": "+5", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#5C6BC0", "coords": { "x": -7.5, "y": 2.5 }
    },
    {
        "id": "cinestill-800t",
        "name": { "vi": "43. Ánh Đèn Neon", "en": "43. Cinestill 800T" },
        "description": { "vi": "Tối ưu cho ánh sáng yếu, tạo quầng sáng và màu sắc đặc trưng của cảnh đêm.", "en": "Optimized for low light, creating halation and characteristic colors of night scenes." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": "2700K, A7-M1.25",
        "settings": { "Black level": "+3", "Gamma": "Movie", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+2", "Color Phase": "+5" },
        "colorDepth": { "R": "-5", "G": "-7", "B": "-7", "C": "+3", "M": "-7", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#F06292", "coords": { "x": -9.0, "y": 4.0 }
    },
    {
        "id": "cinestill-x-bwxx",
        "name": { "vi": "44. Phim Đen Trắng Cũ", "en": "44. Cinestill X - BWXX" },
        "description": { "vi": "Tương phản cao, hạt phim rõ rệt, tái hiện cảm giác phim đen trắng cổ điển.", "en": "High contrast, distinct film grain, recreating the feel of classic B&W movies." },
        "type": "bw", "contrast": "high", "saturation": "high",
        "whiteBalance": "5500K",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "+32", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+1", "C": "+2", "M": "+7", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#757575", "coords": { "x": 8.8, "y": -5.0 }
    },
    {
        "id": "t-max-100",
        "name": { "vi": "45. Phác Họa Chì", "en": "45. T-Max 100" },
        "description": { "vi": "Độ sắc nét cao, hạt phim mịn, tạo ảnh đen trắng chi tiết, sạch sẽ.", "en": "High sharpness, fine grain, creating detailed, clean B&W images." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB, B3-G0.25",
        "settings": { "Black level": "-12", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 82% +5", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "-7", "B": "+7", "C": "+7", "M": "+7", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BDBDBD", "coords": { "x": 7.9, "y": -9.0 }
    },
    {
        "id": "delta-3200",
        "name": { "vi": "46. Hạt Mịn", "en": "46. Delta 3200" },
        "description": { "vi": "Tái tạo cấu trúc hạt phim đặc trưng cho ảnh tài liệu thiếu sáng.", "en": "Recreates film grain structure for low-light documentary." },
        "type": "bw", "contrast": "medium", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-11", "Gamma": "Cine4", "Black Gamma": "Wide +7", "Knee": "Manual 82.5% +0", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "-2" },
        "colorDepth": { "R": "+3", "G": "+2", "B": "+7", "C": "+7", "M": "+4", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#9E9E9E", "coords": { "x": 0.5, "y": -7.0 }
    },
    {
        "id": "kosmo-pan",
        "name": { "vi": "47. Vũ Trụ Đơn Sắc", "en": "47. Kosmo Pan" },
        "description": { "vi": "Vùng tối sâu, tương phản mạnh, mang lại cái nhìn kịch tính.", "en": "Deep blacks, strong contrast, for a dramatic look." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "-8", "Gamma": "Cine3", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +3", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "-2" },
        "colorDepth": { "R": "-4", "G": "+3", "B": "+7", "C": "0", "M": "+7", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#616161", "coords": { "x": 8.3, "y": -4.0 }
    },
    {
        "id": "chroma-fade",
        "name": { "vi": "48. Nhạt Phai", "en": "48. Chroma Fade" },
        "description": { "vi": "Vùng tối được nâng tạo hiệu ứng bạc màu, hoài cổ, nhẹ nhàng.", "en": "Lifted shadows create a faded, nostalgic, and gentle effect." },
        "type": "bw", "contrast": "low", "saturation": "low",
        "whiteBalance": "AWB",
        "settings": { "Black level": "+3", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +2", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "0" },
        "colorDepth": { "R": "+5", "G": "+5", "B": "+7", "C": "+2", "M": "+7", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#E0E0E0", "coords": { "x": -7.8, "y": -5.5 }
    },
    {
        "id": "kodak-tri-x-1600",
        "name": { "vi": "49. Kẻ lang thang", "en": "49. Kodak Tri-X 1600 Pushed" },
        "description": { "vi": "Độ tương phản cao, hạt rõ, hoàn hảo cho khoảnh khắc chân thực.", "en": "High contrast, pronounced grain, perfect for authentic moments." },
        "type": "bw", "contrast": "high", "saturation": "high",
        "whiteBalance": "5500K, A3-G2",
        "notes": { "vi": "Tắt Giảm nhiễu cho JPG. Chụp ISO 1600+ để tăng hạt.", "en": "Turn Off Noise Reduction for JPG. Shoot ISO 1600 or higher to increase Granularity." },
        "settings": { "Black level": "+5", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 77.5% +2", "Color Mode": "Black & White", "Saturation": "+24", "Color Phase": "0" },
        "colorDepth": { "R": "-4", "G": "-1", "B": "+6", "C": "+5", "M": "-3", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#424242", "coords": { "x": 9.3, "y": -3.5 }
    },
    {
        "id": "kodak-tri-x-400",
        "name": { "vi": "50. Ảnh Cũ", "en": "50. Kodak Tri-X 400" },
        "description": { "vi": "Tương phản thấp, hạt mịn, tạo cảm giác ảnh cũ.", "en": "Low contrast, fine grain, feel of an old photo." },
        "type": "bw", "contrast": "low", "saturation": "high",
        "whiteBalance": "5500K, A3-G2",
        "notes": { "vi": "Bật Giảm nhiễu cho JPG & đặt thành Thấp. Chụp ISO 1600+ để tăng hạt.", "en": "Turn On NR for JPG & Set to Low. Shoot ISO 1600+ to increase Granularity." },
        "settings": { "Black level": "+3", "Gamma": "Cine1", "Black Gamma": "Narrow +5", "Knee": "Manual 75% +3", "Color Mode": "Black & White", "Saturation": "+24", "Color Phase": "0" },
        "colorDepth": { "R": "+3", "G": "+3", "B": "+3", "C": "+2", "M": "+3", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#B0BEC5", "coords": { "x": -8.1, "y": -6.4 }
    },
    {
        "id": "neo-max",
        "name": { "vi": "51. Tương Lai Đơn Sắc", "en": "51. Neo Max" },
        "description": { "vi": "Đen trắng hiện đại, tương phản cân bằng, vừa cổ điển vừa vị lai.", "en": "Modern B&W, balanced contrast, both classic and futuristic." },
        "type": "bw", "contrast": "medium", "saturation": "high",
        "whiteBalance": "6000K, B2.5-M1.5",
        "settings": { "Black level": "+2", "Gamma": "Cine1-4", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "+32", "Color Phase": "0" },
        "colorDepth": { "R": "-4", "G": "+5", "B": "+4", "C": "0", "M": "-5", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#757575", "coords": { "x": 2.0, "y": -6.0 }
    },
    {
        "id": "ilford-hp5",
        "name": { "vi": "52. Khoảnh khắc quyết định", "en": "52. Ilford HP5" },
        "description": { "vi": "Tương phản cao, phù hợp nhiếp ảnh tài liệu, nhấn mạnh cảm xúc.", "en": "High contrast for documentary, emphasizing emotion." },
        "type": "bw", "contrast": "high", "saturation": "low",
        "whiteBalance": "AWB, A3",
        "settings": { "Black level": "-12", "Gamma": "Movie", "Black Gamma": "Middle -5", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "0" },
        "colorDepth": { "R": "0", "G": "+3", "B": "0", "C": "+2", "M": "+3", "Y": "0" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#90A4AE", "coords": { "x": 7.6, "y": -1.8 }
    },
    {
        "id": "midred-infra",
        "name": { "vi": "53. Hồng Ngoại", "en": "53. MidRed Infra" },
        "description": { "vi": "Tái tạo hiệu ứng phim hồng ngoại, tán lá trắng, bầu trời đen.", "en": "Recreates infrared film effect, white foliage, dark skies." },
        "type": "bw", "contrast": "high", "saturation": "high",
        "whiteBalance": "AWB, A3",
        "settings": { "Black level": "-10", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "+32", "Color Phase": "+4" },
        "colorDepth": { "R": "-7", "G": "-7", "B": "+7", "C": "+7", "M": "+7", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFFFFF", "coords": { "x": 8.9, "y": 0.5 }
    },
    {
        "id": "dream-neg",
        "name": { "vi": "54. Giấc Mơ Trưa", "en": "54. Dream Neg" },
        "description": { "vi": "Màu sắc ấm áp, mềm mại, mang lại cảm giác mơ màng, lãng mạn.", "en": "Warm, soft colors, providing a dreamy, romantic feeling." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "4500K, A7",
        "settings": { "Black level": "-5", "Gamma": "Cine1 or Cine4", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+25", "Color Phase": "+3" },
        "colorDepth": { "R": "-2", "G": "+5", "B": "-2", "C": "+3", "M": "+3", "Y": "-1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFCC80", "coords": { "x": 3.0, "y": 8.5 }
    },
    {
        "id": "agfa-precisa",
        "name": { "vi": "55. Màu Chuẩn Xác", "en": "55. Agfa Precisa" },
        "description": { "vi": "Độ bão hòa và tương phản cao, tạo màu sắc sống động và chuẩn xác.", "en": "High saturation and contrast, creating vivid and accurate colors." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3500K, A7-G1.5",
        "settings": { "Black level": "+1", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+32", "Color Phase": "+2" },
        "colorDepth": { "R": "+4", "G": "+1", "B": "+7", "C": "+1", "M": "+7", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#673AB7", "coords": { "x": 9.1, "y": 7.8 }
    },
    {
        "id": "redscale-ultra",
        "name": { "vi": "56. Đỏ Rực", "en": "56. RedScale Ultra" },
        "description": { "vi": "Tông màu đỏ và cam bao trùm, tạo hiệu ứng độc đáo, nghệ thuật.", "en": "Dominant red and orange tone, creating a unique, artistic effect." },
        "type": "color", "contrast": "low", "saturation": "low",
        "whiteBalance": ">9900K, B3-G2",
        "notes": { "vi": "Đặt WB tùy chỉnh bằng thẻ màu Teal.", "en": "Set with Custom WB and a Teal Card." },
        "settings": { "Black level": "+5", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "ITU709Matrix", "Saturation": "+7", "Color Phase": "-1" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "+5", "C": "+5", "M": "-7", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FF5722", "coords": { "x": -8.0, "y": 6.8 }
    },
    {
        "id": "zetra-100",
        "name": { "vi": "57. Bạc Hà Mát Lạnh", "en": "57. Zetra 100" },
        "description": { "vi": "Tông màu lạnh, sắc xanh bạc hà đặc trưng, tươi mát, trong lành.", "en": "Cool tone, characteristic mint green hue, fresh and clean." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "4600K, A7-M1.5",
        "settings": { "Black level": "-8", "Gamma": "Cine1", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+20", "Color Phase": "-4" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "-5", "C": "-5", "M": "+3", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#00BCD4", "coords": { "x": 7.3, "y": -1.5 }
    },
    {
        "id": "rose-spectra",
        "name": { "vi": "58. Cánh Hồng", "en": "58. Rose Spectra" },
        "description": { "vi": "Tông màu hồng và đỏ tươi tắn, mềm mại, lý tưởng cho chân dung.", "en": "Fresh pink and red tone, soft, ideal for portraits." },
        "type": "color", "contrast": "low", "saturation": "high",
        "whiteBalance": "4600K, A7-M0.5",
        "settings": { "Black level": "+6", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Pro", "Saturation": "+25", "Color Phase": "+2" },
        "colorDepth": { "R": "-1", "G": "0", "B": "0", "C": "-3", "M": "+5", "Y": "-1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#E91E63", "coords": { "x": -7.0, "y": 7.2 }
    },
    {
        "id": "kodak-vision-200t",
        "name": { "vi": "59. Thành Phố Vàng", "en": "59. Kodak Vision 200T" },
        "description": { "vi": "Tông màu vàng ấm áp, tối ưu cho ánh sáng đèn tungsten.", "en": "Warm golden tone, optimized for tungsten lighting." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "4700K, A7-G1.25",
        "notes": { "vi": "Tắt Gamma Assist!", "en": "Turn Off Gamma Assist!" },
        "settings": { "Black level": "-15", "Gamma": "S-Log2 or S-Log3", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "ITU709Matrix", "Saturation": "+32", "Color Phase": "+5" },
        "colorDepth": { "R": "+1", "G": "+7", "B": "-7", "C": "-7", "M": "+5", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFC107", "coords": { "x": 8.4, "y": 8.4 }
    },
    {
        "id": "kodak-vision-200t-v2",
        "name": { "vi": "60. Phố Cát", "en": "60. Kodak Vision 200T-V2" },
        "description": { "vi": "Màu sắc ấm áp, ngả vàng cát, hoài niệm và bụi bặm.", "en": "Warm, sandy-yellow hue, nostalgic and dusty feel." },
        "type": "color", "contrast": "low", "saturation": "high",
        "whiteBalance": "4400K, A7-G1",
        "settings": { "Black level": "0", "Gamma": "Cine1", "Black Gamma": "Middle +7", "Knee": "Manual 75% +5", "Color Mode": "Still", "Saturation": "+25", "Color Phase": "+3" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "0", "C": "0", "M": "+5", "Y": "+3" },
        "detailSettings": { "Level": "-7", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 5", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFD54F", "coords": { "x": -6.5, "y": 7.7 }
    },
    {
        "id": "ayon-200",
        "name": { "vi": "61. Sa Mạc Bỏng Cháy", "en": "61. Ayon 200" },
        "description": { "vi": "Tông màu vàng cam bão hòa, tái hiện cái nóng của sa mạc.", "en": "Saturated yellow-orange tone, recreating desert heat." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "8000K, A7-G5.5",
        "settings": { "Black level": "-12", "Gamma": "Cine4", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3", "Saturation": "+32", "Color Phase": "+7" },
        "colorDepth": { "R": "+4", "G": "+5", "B": "0", "C": "0", "M": "-3", "Y": "+7" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FF9800", "coords": { "x": 9.4, "y": 8.9 }
    },
    {
        "id": "phoenix-harman",
        "name": { "vi": "62. Lửa Phượng Hoàng", "en": "62. Phoenix Harman" },
        "description": { "vi": "Màu sắc rực rỡ, đỏ và vàng, tương phản cao, mạnh mẽ.", "en": "Vibrant red and yellow, high contrast, powerful." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "8500K, B3.5-G1",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 105% +5", "Color Mode": "S-Cinetone", "Saturation": "+32", "Color Phase": "+1" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "+2", "C": "+5", "M": "+5", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#F44336", "coords": { "x": 9.6, "y": 9.2 }
    },
    {
        "id": "phenomena",
        "name": { "vi": "63. Huyền Ảo", "en": "63. Phenomena" },
        "description": { "vi": "Màu sắc bão hòa cao, độc đáo, tạo cái nhìn siêu thực.", "en": "Highly saturated, unique colors, creating a surreal look." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "AWB, A3",
        "settings": { "Black level": "-5", "Gamma": "Cine1-4", "Black Gamma": "Wide +7", "Knee": "Manual 80% +4", "Color Mode": "Pro", "Saturation": "+25", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+7", "C": "+7", "M": "+5", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#9C27B0", "coords": { "x": 4.5, "y": 9.5 }
    },
    {
        "id": "acidnom",
        "name": { "vi": "64. Xanh Acid", "en": "64. Acidnom" },
        "description": { "vi": "Xanh lá cây và vàng chanh nổi bật, hiệu ứng thị giác mạnh.", "en": "Prominent green and lime-yellow, strong visual effect." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "3400K, A7-M1.75",
        "settings": { "Black level": "-6", "Gamma": "Still", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+32", "Color Phase": "0" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+2", "C": "+7", "M": "-5", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#8BC34A", "coords": { "x": 1.5, "y": -8.0 }
    },
    {
        "id": "estra-500",
        "name": { "vi": "65. Dạ Khúc Ánh Trăng", "en": "65. Estra 500" },
        "description": { "vi": "Màu sắc lạnh, ám xanh tím, tĩnh lặng và bí ẩn của đêm trăng.", "en": "Cool colors, blue-purple cast, quiet and mysterious moonlight." },
        "type": "color", "contrast": "medium", "saturation": "low",
        "whiteBalance": "8600K, B2.5-M3",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Middle -7", "Knee": "Manual 82.5% +4", "Color Mode": "Still", "Saturation": "-8", "Color Phase": "+1" },
        "colorDepth": { "R": "-6", "G": "+7", "B": "+1", "C": "+3", "M": "+7", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#7986CB", "coords": { "x": -3.0, "y": 1.5 }
    },
    {
        "id": "arista-edu-100",
        "name": { "vi": "66. Đơn Sắc Tối Giản", "en": "66. Arista Edu 100" },
        "description": { "vi": "Tương phản cao, vùng đen sâu, tập trung vào hình khối, đường nét.", "en": "High contrast, deep blacks, focusing on shapes and lines." },
        "type": "bw", "contrast": "high", "saturation": "high",
        "whiteBalance": "5500K",
        "settings": { "Black level": "-15", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +2", "Color Mode": "Black & White", "Saturation": "+28", "Color Phase": "0" },
        "colorDepth": { "R": "-3", "G": "+4", "B": "+3", "C": "+3", "M": "+3", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#616161", "coords": { "x": 8.7, "y": -6.8 }
    },
    {
        "id": "x-tarr",
        "name": { "vi": "67. Kịch Tính Đen Trắng", "en": "67. X-Tarr" },
        "description": { "vi": "Tương phản, bão hòa tối đa, tạo cái nhìn đen trắng kịch tính.", "en": "Maximum contrast and saturation, creating a dramatic B&W look." },
        "type": "bw", "contrast": "high", "saturation": "high",
        "whiteBalance": "5500K",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +5", "Color Mode": "Black & White", "Saturation": "+32", "Color Phase": "0" },
        "colorDepth": { "R": "+4", "G": "+7", "B": "+7", "C": "+7", "M": "+7", "Y": "+7" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#212121", "coords": { "x": 9.8, "y": -9.8 }
    },
    {
        "id": "magicspice",
        "name": { "vi": "68. Gia Vị Ma Thuật", "en": "68. MagicSpice" },
        "description": { "vi": "Tông màu ấm, ngả vàng đỏ, mang lại cảm giác ấm cúng.", "en": "Warm tone, yellow-red cast, providing a cozy feeling." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "7000K, B4-M1.25",
        "settings": { "Black level": "-12", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Manual 75% +5", "Color Mode": "Still", "Saturation": "+17", "Color Phase": "-1" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "-3", "C": "-3", "M": "-5", "Y": "+4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BF360C", "coords": { "x": 6.8, "y": 6.8 }
    },
    {
        "id": "amarelo-300",
        "name": { "vi": "69. Vỏ Chanh Vàng", "en": "69. Amarelo 300" },
        "description": { "vi": "Tông màu vàng chanh tươi sáng, hơi gắt, tràn đầy năng lượng.", "en": "Bright and slightly sharp lemon-yellow tone, energetic." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "4200K, A7-G0.25",
        "settings": { "Black level": "+4", "Gamma": "Still", "Black Gamma": "Wide +7", "Knee": "Manual 75% +5", "Color Mode": "Still", "Saturation": "+20", "Color Phase": "-4" },
        "colorDepth": { "R": "-1", "G": "+7", "B": "0", "C": "-3", "M": "-4", "Y": "-2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FDD835", "coords": { "x": -5.5, "y": 5.0 }
    },
    {
        "id": "gaf-500",
        "name": { "vi": "70. Rêu Phong", "en": "70. GAF 500" },
        "description": { "vi": "Tông màu xanh rêu, nâu đất, tạo cảm giác cổ kính, trầm mặc.", "en": "Moss-green, earthy-brown tone, creating an ancient feel." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "5300K, A7-M0.75",
        "settings": { "Black level": "+3", "Gamma": "Still", "Black Gamma": "Wide +7", "Knee": "Manual 75% +4", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "0" },
        "colorDepth": { "R": "+3", "G": "+5", "B": "-3", "C": "-3", "M": "-3", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#795548", "coords": { "x": -6.8, "y": -7.8 }
    },
    {
        "id": "vespera-nightime",
        "name": { "vi": "71. Đêm Lam Tím", "en": "71. Vespera - Nightime" },
        "description": { "vi": "Màu xanh chàm, tím sâu, tối ưu cho cảnh đêm, huyền ảo.", "en": "Deep indigo and violet, optimized for night scenes, magical." },
        "type": "color", "contrast": "medium", "saturation": "low",
        "whiteBalance": "2500K, B4-G2.5",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Middle -7", "Knee": "Manual 82.5% +4", "Color Mode": "Still", "Saturation": "-10", "Color Phase": "+7" },
        "colorDepth": { "R": "-6", "G": "+7", "B": "+1", "C": "+3", "M": "+7", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#311B92", "coords": { "x": -2.5, "y": 0.5 }
    },
    {
        "id": "veniliqum-night",
        "name": { "vi": "72. Ngọc Lục Bảo Đêm", "en": "72. Veniliqum - Night" },
        "description": { "vi": "Tông xanh lục bảo đậm, bão hòa cao dưới đèn đêm, sang trọng.", "en": "Deep, highly saturated emerald green under night lights, luxurious." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3000K, A7-G7",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide +7", "Knee": "Manual 105% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+32", "Color Phase": "+5" },
        "colorDepth": { "R": "+5", "G": "-1", "B": "+2", "C": "+5", "M": "+5", "Y": "+3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#00695C", "coords": { "x": 7.7, "y": -6.5 }
    },
    {
        "id": "gold-luxe-nighttime",
        "name": { "vi": "73. Vàng 24K", "en": "73. Gold Luxe - Nighttime" },
        "description": { "vi": "Tông vàng kim loại ấm áp, sang trọng, cho cảnh đêm lấp lánh.", "en": "Warm, luxurious metallic gold tone for sparkling night scenes." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "5500K, A7-M0.75",
        "settings": { "Black level": "+2", "Gamma": "Still", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+18", "Color Phase": "+7" },
        "colorDepth": { "R": "+5", "G": "-1", "B": "+2", "C": "+5", "M": "+5", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFB300", "coords": { "x": -4.0, "y": 7.0 }
    },
    {
        "id": "eastman-color-negative-ii-100t",
        "name": { "vi": "74. Âm Bản Cổ Điển", "en": "74. Eastman Color Negative II - 100T" },
        "description": { "vi": "Tông màu lạnh, ám xanh, tái tạo cảm giác phim âm bản xưa.", "en": "Cool, blue-tinted tone, recreating the feel of old negative film." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "8200K, B4.5-G1.75",
        "settings": { "Black level": "-10", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+16", "Color Phase": "+2" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "-6", "C": "-5", "M": "+7", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#2196F3", "coords": { "x": 6.5, "y": 3.0 }
    },
    {
        "id": "kodak-vision3-50d",
        "name": { "vi": "75. Thị Giác Mùa Hè", "en": "75. Kodak Vision3 50D" },
        "description": { "vi": "Màu sắc rực rỡ, ấm áp, hoàn hảo cho ánh sáng ban ngày.", "en": "Vibrant, warm colors, perfect for daylight." },
        "type": "color", "contrast": "high", "saturation": "high",
        "whiteBalance": "3300K, A7-G0.75",
        "settings": { "Black level": "-10", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+32", "Color Phase": "+2" },
        "colorDepth": { "R": "+4", "G": "+7", "B": "-6", "C": "+4", "M": "+6", "Y": "+5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFEB3B", "coords": { "x": 8.6, "y": 9.3 }
    },
    {
        "id": "solara-100",
        "name": { "vi": "76. Nắng Phai", "en": "76. Solara 100" },
        "description": { "vi": "Tông màu ấm, ngả vàng, bão hòa thấp, tạo cảm giác hoài cổ.", "en": "Warm, yellowish tone, low saturation, creates a nostalgic feel." },
        "type": "color", "contrast": "low", "saturation": "medium",
        "whiteBalance": "4200K, A7-M2",
        "settings": { "Black level": "+5", "Gamma": "Still", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +5", "Color Mode": "Still", "Saturation": "+14", "Color Phase": "-3" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-3", "C": "-7", "M": "-4", "Y": "-1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFF176", "coords": { "x": -5.0, "y": 6.5 }
    },
    {
        "id": "kodak-pro-image-100",
        "name": { "vi": "77. Ảnh Chuyên Nghiệp", "en": "77. Kodak Pro Image 100" },
        "description": { "vi": "Màu sắc trung thực, tông da đẹp, lựa chọn tin cậy cho chân dung.", "en": "True colors, beautiful skin tones, a reliable choice for portraits." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "4000K, A7-G1",
        "settings": { "Black level": "+6", "Gamma": "S-Cinetone/Cine4", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+30", "Color Phase": "-2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+3", "C": "+5", "M": "+3", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFB74D", "coords": { "x": 5.0, "y": 5.0 }
    },
    {
        "id": "candy-look",
        "name": { "vi": "78. Kẹo Ngọt", "en": "78. Candy Look" },
        "description": { "vi": "Màu sắc rực rỡ, tươi sáng như kẹo, mang lại cảm giác vui tươi.", "en": "Bright, vibrant colors like candy, providing a cheerful feeling." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "AWB, A2-M0.75",
        "settings": { "Black level": "-4", "Gamma": "Cine4", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+27", "Color Phase": "-3" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+1", "C": "+4", "M": "+2", "Y": "-5" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#EC407A", "coords": { "x": 6.0, "y": 9.0 }
    },
    {
        "id": "aeris-100",
        "name": { "vi": "79. Không Khí Trong Lành", "en": "79. Aeris 100" },
        "description": { "vi": "Tông xanh da trời và trắng sáng, tạo cảm giác trong lành.", "en": "Sky-blue and bright white tone, creating a fresh feeling." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "AWB, B2-G2",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Wide +7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+30", "Color Phase": "+2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+7", "C": "-5", "M": "-3", "Y": "-4" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#29B6F6", "coords": { "x": 3.5, "y": 2.0 }
    },
    {
        "id": "sundune-400",
        "name": { "vi": "80. Cồn Cát Vàng", "en": "80. Sundune 400" },
        "description": { "vi": "Màu vàng cát ấm áp, bão hòa cao, gợi hình ảnh cồn cát.", "en": "Warm, highly saturated sandy yellow, evoking dunes." },
        "type": "color", "contrast": "medium", "saturation": "high",
        "whiteBalance": "AWB, A2-G1.75",
        "settings": { "Black level": "+4", "Gamma": "S-Cinetone", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+32", "Color Phase": "+3" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+4", "C": "-5", "M": "-3", "Y": "-3" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FFA000", "coords": { "x": 4.0, "y": 8.0 }
    },
    {
        "id": "kodak-vision3-250d",
        "name": { "vi": "81. Điện Ảnh 250D", "en": "81. Kodak Vision3 250D" },
        "description": { "vi": "Bão hòa cao, tông màu ấm, giả lập màu phim điện ảnh ban ngày.", "en": "High saturation, warm tone, simulates daylight cinematic film." },
        "type": "color", "contrast": "low", "saturation": "high",
        "whiteBalance": "3700K, A7-G1",
        "settings": { "Black level": "+9", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+32", "Color Phase": "+3" },
        "colorDepth": { "R": "0", "G": "+3", "B": "+2", "C": "+2", "M": "-3", "Y": "+1" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#FF8F00", "coords": { "x": -6.0, "y": 8.3 }
    },
    {
        "id": "orthochromatic",
        "name": { "vi": "82. Đơn Sắc Cổ Điển", "en": "82. Orthochromatic" },
        "description": { "vi": "Giả lập phim đen trắng cổ điển không nhạy với màu đỏ.", "en": "Simulates classic orthochromatic B&W film, not sensitive to red." },
        "type": "bw", "contrast": "high", "saturation": "medium",
        "whiteBalance": "AWB, A3-M2.75",
        "settings": { "Black level": "-12", "Gamma": "Movie", "Black Gamma": "Narrow -7", "Knee": "105% +5", "Color Mode": "Still", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "+7", "G": "+7", "B": "-7", "C": "-7", "M": "+7", "Y": "+7" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#BDBDBD", "coords": { "x": 7.4, "y": -4.5 }
    },
    {
        "id": "santa-color-100",
        "name": { "vi": "83. Ấm cúng", "en": "83. Santa Color 100" },
        "description": { "vi": "Tông màu ấm, sắc đỏ và xanh lá đặc trưng, không khí lễ hội.", "en": "Warm tone, characteristic red and green hues, festive atmosphere." },
        "type": "color", "contrast": "high", "saturation": "medium",
        "whiteBalance": "AWB, A5-G0.25",
        "settings": { "Black level": "-7", "Gamma": "Cine3", "Black Gamma": "Narrow -7", "Knee": "105% +5", "Color Mode": "Still", "Saturation": "+13", "Color Phase": "+4" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "-4", "C": "-5", "M": "+4", "Y": "+2" },
        "detailSettings": { "Level": "0", "Mode": "Manual", "V/H Balance": "+2", "B/W Balance": "Type 3", "Limit": "7", "Crispening": "7", "Hi-Light Detail": "4" },
        "personalityColor": "#EF5350", "coords": { "x": 6.9, "y": 6.0 }
    }
])
export default recipesData;
