name = "sonycolorlab"
main = "src/index.js" # your entry point, adjust as needed
compatibility_date = "2025-09-11" # today's date or your targeted date
type = "javascript" # or "webpack" or "rust" depending on your project
