// File Path: src/services/api.js
/**
 * api.js
 * This module handles all interactions with external services.
 */

// --- Local Module Imports ---
// import { API_KEY } from './state.js'; // Removed for mock implementation

/**
 * Initializes the Firebase application.
 */
export function initializeFirebase() {
    return null;
}

/**
 * Fetches the latest trending recipe IDs.
 */
export async function fetchTrendingRecipeIds() {
    // Mock trending IDs
    const fallbackIDs = ["scl-001", "scl-007", "scl-008", "scl-015", "scl-027"];
    return Promise.resolve(fallbackIDs);
}

/**
 * Makes a POST request to the Gemini API to generate content.
 * @param {string} prompt - The complete prompt to send to the API.
 * @param {AbortSignal} signal - An AbortSignal to allow for request cancellation.
 * @returns {Promise<object>} A promise that resolves to the parsed JSON response from the API.
 */
export async function callGeminiAPI(prompt, signal) {
    console.log("[MOCK API] callGeminiAPI called with prompt:", prompt);

    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    // Check if signal is aborted
    if (signal && signal.aborted) {
        throw new DOMException('Aborted', 'AbortError');
    }

    // Mock response data simulating a new recipe generated by AI
    const mockRecipe = {
        "name": "Mock AI Recipe",
        "description": "This is a mock recipe generated by the offline development environment. It simulates the structure of a real AI-generated recipe.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["mock", "offline", "ai-generated"],
        "whiteBalance": "5500K, A0-M0",
        "settings": {
            "Black level": "0",
            "Gamma": "Cine1",
            "Black Gamma": "Wide 0",
            "Knee": "Auto",
            "Color Mode": "Pro",
            "Saturation": "0",
            "Color Phase": "0"
        },
        "colorDepth": { "R": "0", "G": "0", "B": "0", "C": "0", "M": "0", "Y": "0" },
        "detailSettings": {
            "level": 0,
            "mode": "Manual",
            "vhBalance": "0",
            "bwBalance": "Type 3",
            "limit": 3,
            "crispening": 0,
            "hiLightDetail": 0
        }
    };

    // Return the mock object directly
    return mockRecipe;
}
