const recipesData = [
    {
        "id": "scl-001",
        "name": "SCL-001: Mojave Sun",
        "description": "A nostalgic, sun-drenched style that bathes scenes in the warm glow of golden hour.\nPerfect for travel and lifestyle, it recreates rich yellows and deep blues, evoking the feeling of an endless summer road trip.",
        "type": "color",
        "contrast": "normal",
        "saturation": "high",
        "tags": ["nostalgic", "sun-drenched", "warm", "travel", "lifestyle", "summer", "golden-hour"],
        "whiteBalance": "7000K, B3-M1.5",
        "settings": { "Black level": "-7", "Gamma": "Cine1", "Black Gamma": "Wide +5", "Knee": "Manual 75% +2", "Color Mode": "S-Gamut3", "Saturation": "+25", "Color Phase": "+1" },
        "colorDepth": { "R": "-1", "G": "+1", "B": "+5", "C": "+4", "M": "-2", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-002",
        "name": "SCL-002: Kyoto Jade",
        "description": "A serene and subtle palette defined by rich jade tones and gentle skin colors.\nIdeal for contemplative portraits, street photography, and landscapes, creating a peaceful, painterly atmosphere.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["serene", "subtle", "portrait", "street-photography", "landscape", "peaceful", "painterly"],
        "whiteBalance": "3700K, A7-M0.5",
        "settings": { "Black level": "0", "Gamma": "Cine1", "Black Gamma": "Wide +7", "Knee": "Manual 80% +3", "Color Mode": "Pro", "Saturation": "+12", "Color Phase": "-4" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "-2", "C": "-2", "M": "-5", "Y": "-3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-003",
        "name": "SCL-003: Caspian Blue",
        "description": "A warm tone, cinematic profile with distinctive deep blues and rich, crushed blacks.\nIt lends a moody, atmospheric quality to images, perfect for urban nightscapes, dramatic portraits, and storytelling.",
        "type": "color",
        "contrast": "high",
        "saturation": "normal",
        "tags": ["cinematic", "cool-tone", "deep-blues", "moody", "atmospheric", "urban-night", "dramatic-portrait", "storytelling"],
        "whiteBalance": "8000K, B2-M2",
        "settings": { "Black level": "-15", "Gamma": "Cine4", "Black Gamma": "Middle +4", "Knee": "Manual 85% +4", "Color Mode": "S-Gamut3.Cine", "Saturation": "+22", "Color Phase": "+7" },
        "colorDepth": { "R": "0", "G": "-2", "B": "+4", "C": "+5", "M": "+5", "Y": "+1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-004",
        "name": "SCL-004: Tuscan Ochre",
        "description": "A vibrant, high-saturation style with warm, earthy reds and yellows.\nIt brings a bold, sun-baked intensity to images, reminiscent of classic European travel photography.",
        "type": "color",
        "contrast": "normal",
        "saturation": "high",
        "tags": ["vibrant", "high-saturation", "earthy-reds", "warm-yellows", "bold", "sun-baked", "classic-european-travel"],
        "whiteBalance": "4700K, A2-M0.5",
        "settings": { "Black level": "+2", "Gamma": "S-Cinetone", "Black Gamma": "Wide -5", "Knee": "Auto", "Color Mode": "S-Gamut3.Cine", "Saturation": "+25", "Color Phase": "+3" },
        "colorDepth": { "R": "-2", "G": "+6", "B": "+4", "C": "+5", "M": "+5", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-005",
        "name": "SCL-005: Somerset Meadow",
        "description": "A soft, pastel-like palette with gentle contrast and low saturation.\nIt renders skin tones beautifully and gives landscapes a dreamy, ethereal quality, perfect for romantic and fine-art portraits.",
        "type": "color",
        "contrast": "soft",
        "saturation": "low",
        "tags": ["pastel", "soft-contrast", "low-saturation", "dreamy", "ethereal", "romantic-portrait", "fine-art"],
        "whiteBalance": "4200K, A6-M2",
        "settings": { "Black level": "-8", "Gamma": "Cine1", "Black Gamma": "Middle -5", "Knee": "Manual 90% +1", "Color Mode": "Pro", "Saturation": "+8", "Color Phase": "+3" },
        "colorDepth": { "R": "-3", "G": "+6", "B": "-2", "C": "-3", "M": "-4", "Y": "+4" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-006",
        "name": "SCL-006: Faded Cine",
        "description": "A stylized look with heavily lifted blacks and muted colors, creating a soft, hazy effect.\nIt evokes a sense of nostalgia and is ideal for fashion, editorial, and lifestyle photography aiming for a vintage-modern feel.",
        "type": "color",
        "contrast": "soft",
        "saturation": "muted",
        "tags": ["stylized", "lifted-blacks", "soft-colors", "hazy", "nostalgic", "fashion", "editorial", "lifestyle", "vintage-modern"],
        "whiteBalance": "3600K, A6-M1.5",
        "settings": { "Black level": "+15", "Gamma": "Cine1", "Black Gamma": "Narrow +7", "Knee": "Manual 90% -2", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-4" },
        "colorDepth": { "R": "-2", "G": "+5", "B": "-3", "C": "+3", "M": "+5", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-007",
        "name": "SCL-007: Dynachrome '75",
        "description": "A high-contrast, moody profile with deep blacks and a dramatic, cool color shift.\nIt emphasizes texture and form, creating a strong graphic style reminiscent of vintage documentary slide film.",
        "type": "color",
        "contrast": "high",
        "saturation": "normal",
        "tags": ["high-contrast", "moody", "deep-blacks", "cool-color-shift", "graphic", "classic-slide-film"],
        "whiteBalance": "4700K, A7-G0.5",
        "settings": { "Black level": "-15", "Gamma": "S-Cinetone", "Black Gamma": "Wide -7", "Knee": "Auto", "Color Mode": "Pro", "Saturation": "+15", "Color Phase": "+2" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "-7", "C": "-6", "M": "+3", "Y": "+3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-008",
        "name": "SCL-008: Modern Classic",
        "description": "A clean, vibrant, and contemporary style built on modern color science.\nIt delivers rich, pleasing colors with smooth tonal transitions, making it a versatile choice for everyday shooting, from portraits to products.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["clean", "vibrant", "contemporary", "modern-color-science", "rich-colors", "smooth-tonal-transitions", "versatile", "everyday", "portrait", "product"],
        "whiteBalance": "4000K, A7-M2",
        "settings": { "Black level": "+2", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+16", "Color Phase": "-3" },
        "colorDepth": { "R": "0", "G": "+6", "B": "+4", "C": "-2", "M": "+3", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-009",
        "name": "SCL-009: Urban Teal",
        "description": "A muted, low-saturation color profile with a distinctive cyan-teal cast in the shadows and mid-tones.\nIt creates a subtle, gentle, and slightly melancholic mood, perfect for street photography and urban exploration.",
        "type": "color",
        "contrast": "normal",
        "saturation": "low",
        "tags": ["muted-color", "low-saturation", "cyan-teal", "subtle", "gentle", "melancholy", "street-photography", "urban-exploration"],
        "whiteBalance": "4000K, A7-M0.5",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Middle -7", "Knee": "Manual 80% +2", "Color Mode": "Still", "Saturation": "-2", "Color Phase": "+2" },
        "colorDepth": { "R": "-5", "G": "+6", "B": "+3", "C": "+4", "M": "-6", "Y": "-1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-010",
        "name": "SCL-010: Cinema Verde",
        "description": "A cinematic style with very low saturation and a subtle green tint, designed to emulate motion picture film.\nIt provides a flat, neutral base, ideal for shots requiring a desaturated, atmospheric feel.",
        "type": "color",
        "contrast": "low",
        "saturation": "very-low",
        "tags": ["cinematic", "very-low-saturation", "subtle-green-tint", "film-emulation", "flat", "neutral", "desaturated", "atmospheric"],
        "whiteBalance": "4000K, A7-M0.25",
        "settings": { "Black level": "+5", "Gamma": "Cine1", "Black Gamma": "Wide -4", "Knee": "Manual 85% +2", "Color Mode": "Pro", "Saturation": "-7", "Color Phase": "+1" },
        "colorDepth": { "R": "-3", "G": "+7", "B": "-2", "C": "+5", "M": "+3", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-011",
        "name": "SCL-011: Midnight Halogen",
        "description": "A night-specific formula that transforms artificial city lights into vibrant blues and cyans, while maintaining good highlight control.\nIt creates a futuristic, cyberpunk-inspired aesthetic.",
        "type": "color",
        "contrast": "high",
        "saturation": "normal",
        "tags": ["night-specific", "city-lights", "vibrant-blues", "cyan-teal", "highlight-control", "futuristic", "cyberpunk"],
        "whiteBalance": "2700K, A7-M1.25",
        "settings": { "Black level": "-2", "Gamma": "Cine4", "Black Gamma": "Wide +7", "Knee": "Manual 90% +3", "Color Mode": "Still", "Saturation": "+5", "Color Phase": "+5" },
        "colorDepth": { "R": "-5", "G": "-7", "B": "-6", "C": "+4", "M": "-7", "Y": "-5" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-012",
        "name": "SCL-012: Amber Glow",
        "description": "A warm, soft, and nostalgic profile with a gentle amber cast.\nIt excels at creating a cozy and intimate feel, perfect for golden hour portraits, family photos, and vintage-inspired shots.",
        "type": "color",
        "contrast": "soft",
        "saturation": "normal",
        "tags": ["warm", "soft", "nostalgic", "amber-tint", "intimate", "golden-hour-portrait", "family-photos", "vintage-inspired"],
        "whiteBalance": "4300K, A7-M0.25",
        "settings": { "Black level": "0", "Gamma": "S-Cinetone", "Black Gamma": "Middle +2", "Knee": "Auto", "Color Mode": "Pro", "Saturation": "+5", "Color Phase": "+1" },
        "colorDepth": { "R": "+2", "G": "+5", "B": "+1", "C": "+2", "M": "+4", "Y": "+3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-013",
        "name": "SCL-013: Flatiron Mist",
        "description": "An incredibly versatile, low-contrast profile that utilizes an S-Log gamma to maximize dynamic range.\nIt produces a flat, soft image with rich colors, perfect for harsh lighting conditions or as a robust base for post-production.",
        "type": "color",
        "contrast": "low",
        "saturation": "normal",
        "tags": ["versatile", "low-contrast", "s-log", "maximized-dynamic-range", "flat-image", "soft", "rich-colors", "harsh-lighting", "post-production"],
        "whiteBalance": "4500K, A7-M1",
        "settings": { "Black level": "-15", "Gamma": "S-Log2", "Black Gamma": "Middle -7", "Knee": "Manual 75% +5", "Color Mode": "S-Gamut3", "Saturation": "+22", "Color Phase": "+3" },
        "colorDepth": { "R": "+3", "G": "+5", "B": "+5", "C": "+7", "M": "+7", "Y": "-3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-014",
        "name": "SCL-014: Magenta Bloom",
        "description": "A vibrant, powerful style with a distinctive magenta cast, emulating a popular slide film.\nIdeal for landscapes and nature, making flowers and sunsets pop with intense, dramatic colors.",
        "type": "color",
        "contrast": "normal",
        "saturation": "vibrant",
        "tags": ["vibrant", "powerful", "magenta-cast", "slide-film", "landscape", "nature", "flowers", "sunsets", "intense-colors", "dramatic"],
        "whiteBalance": "3900K, A7-M0.25",
        "settings": { "Black level": "-8", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 80% +4", "Color Mode": "Pro", "Saturation": "+12", "Color Phase": "-1" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+1", "C": "+2", "M": "-7", "Y": "0" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-015",
        "name": "SCL-015: Vintage Slide",
        "description": "A neutral, slightly faded style with a subtle green-cyan tint in the shadows.\nIt evokes the feeling of looking through old family slide films, perfect for nostalgic portraits and everyday scenes.",
        "type": "color",
        "contrast": "normal",
        "saturation": "faded",
        "tags": ["warm", "faded", "green-tint", "old-family-slides", "nostalgic-portrait", "everyday-scenes"],
        "whiteBalance": "3600K, A7-M1",
        "settings": { "Black level": "-2", "Gamma": "Cine1", "Black Gamma": "Middle -7", "Knee": "Manual 80% +4", "Color Mode": "Pro", "Saturation": "+10", "Color Phase": "-1" },
        "colorDepth": { "R": "+3", "G": "+5", "B": "-4", "C": "+2", "M": "+6", "Y": "+5" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-016",
        "name": "SCL-016: Everyday Natural",
        "description": "A clean, balanced, and versatile profile with moderate saturation and natural skin tones.\nThis is a go-to choice for a wide range of situations, providing an authentic look with a subtle filmic feel.",
        "type": "color",
        "contrast": "normal",
        "saturation": "moderate",
        "tags": ["clean", "balanced", "versatile", "natural-skin-tones", "all-situations", "authentic-look", "subtle-film-feel"],
        "whiteBalance": "3900K, A7",
        "settings": { "Black level": "0", "Gamma": "S-Cinetone", "Black Gamma": "Wide +2", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+12", "Color Phase": "-1" },
        "colorDepth": { "R": "-1", "G": "+5", "B": "+3", "C": "+2", "M": "-3", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-017",
        "name": "SCL-017: Soft Portrait",
        "description": "Characterized by soft contrast and a gentle magenta cast, this formula is perfect for flattering portraits.\nIt renders skin tones with a smooth, delicate quality, creating a refined and elegant look.",
        "type": "color",
        "contrast": "soft",
        "saturation": "muted",
        "tags": ["soft-contrast", "gentle-magenta", "flattering-portraits", "smooth-skin-tones", "delicate", "elegant"],
        "whiteBalance": "4100K, A7-M0.25",
        "settings": { "Black level": "-7", "Gamma": "S-Cinetone", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "Pro", "Saturation": "+7", "Color Phase": "0" },
        "colorDepth": { "R": "0", "G": "+2", "B": "+3", "C": "+2", "M": "-6", "Y": "0" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-018",
        "name": "SCL-018: Vector Graphic",
        "description": "A bold, high-contrast style with super-saturated, almost artificial colors and deep blacks.\nIt creates a strong graphic look, ideal for abstract subjects, modern architecture, and experimental photography.",
        "type": "color",
        "contrast": "high",
        "saturation": "super-saturated",
        "tags": ["bold", "high-contrast", "super-saturated", "artificial-colors", "deep-blacks", "graphic", "abstract", "modern-architecture", "experimental-photography"],
        "whiteBalance": "4000K, A5-M0.5",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 92.5% +5", "Color Mode": "S-Gamut3.Cine", "Saturation": "+30", "Color Phase": "+6" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "+5", "C": "+5", "M": "+2", "Y": "+1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-019",
        "name": "SCL-019: Pop Art",
        "description": "An explosion of color. This formula pushes saturation to the maximum, creating a super-vibrant, high-energy style.\nPerfect for making bold statements and capturing the fun, playful side of life.",
        "type": "color",
        "contrast": "high",
        "saturation": "maximum",
        "tags": ["color-explosion", "maximum-saturation", "super-vibrant", "high-energy", "bold-statements", "playful-side"],
        "whiteBalance": "3700K, A5-M1",
        "settings": { "Black level": "0", "Gamma": "Still", "Black Gamma": "Middle +7", "Knee": "Manual 85% +3", "Color Mode": "S-Gamut3", "Saturation": "+28", "Color Phase": "-1" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+7", "C": "+7", "M": "+7", "Y": "+5" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-020",
        "name": "SCL-020: Autumn Haze",
        "description": "A modern take on classic warm film stocks, utilizing S-Cinetone for smooth tones.\nIt delivers a cozy feel, with slightly muted greens and yellows, perfect for capturing the essence of a misty autumn day.",
        "type": "color",
        "contrast": "normal",
        "saturation": "muted",
        "tags": ["modern-take", "classic-warm-film", "s-cinetone", "smooth-tones", "cozy", "subtle-greens", "yellows", "misty-autumn-day"],
        "whiteBalance": "4600K, A7-G1.25",
        "settings": { "Black level": "+2", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+20", "Color Phase": "+5" },
        "colorDepth": { "R": "+3", "G": "-4", "B": "-5", "C": "-3", "M": "+3", "Y": "-1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-021",
        "name": "SCL-021: Muted Pastels",
        "description": "A soft and subtle style with moderate saturation and gentle tones.\nIt's versatile for everyday shooting, lending images a peaceful and pleasant feel without being overwhelmed by color.",
        "type": "color",
        "contrast": "soft",
        "saturation": "moderate",
        "tags": ["soft", "subtle", "moderate-saturation", "soft-tones", "versatile", "everyday-shooting", "peaceful", "pleasant", "not-overwhelmed-by-color"],
        "whiteBalance": "4500K, A7-M0.75",
        "settings": { "Black level": "+2", "Gamma": "Cine1", "Black Gamma": "Wide -7", "Knee": "Manual 85% +1", "Color Mode": "Pro", "Saturation": "+8", "Color Phase": "-1" },
        "colorDepth": { "R": "-4", "G": "+7", "B": "-3", "C": "-5", "M": "+5", "Y": "+4" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-022",
        "name": "SCL-022: Neutral Standard",
        "description": "A neutral, true-to-life profile designed for accuracy.\nIt provides a clean, standard look with minimal color shifts, making it a great, reliable base for any type of photography.",
        "type": "color",
        "contrast": "normal",
        "saturation": "low",
        "tags": ["neutral", "true-to-life", "accuracy", "clean", "standard-look", "minimal-color-shift", "reliable-base", "any-type-of-photography"],
        "whiteBalance": "4000K, A7-M0.25",
        "settings": { "Black level": "0", "Gamma": "S-Cinetone", "Black Gamma": "Wide -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+2", "Color Phase": "+1" },
        "colorDepth": { "R": "+1", "G": "+7", "B": "0", "C": "+3", "M": "+2", "Y": "+1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-023",
        "name": "SCL-023: Alpine Cool",
        "description": "A cool-toned formula with a high Kelvin temperature, giving images a clean, crisp blue cast.\nIt's well-suited for emphasizing cold light in urban or mountain landscapes, creating a clean and edgy aesthetic.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["cool-tone", "high-kelvin", "clean-blue-cast", "sharp", "cold-light", "urban-landscape", "mountain", "clean-aesthetic", "crisp"],
        "whiteBalance": "7000K, B5-M0.25",
        "settings": { "Black level": "-9", "Gamma": "S-Cinetone", "Black Gamma": "Middle +7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+8", "Color Phase": "+2" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "+3", "C": "-5", "M": "+3", "Y": "-2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-024",
        "name": "SCL-024: Arctic Negative",
        "description": "Pushing white balance to its coldest, this formula creates a unique, stylized look with a deep blue-green cast.\nIt's perfect for experimental, moody, and atmospheric photography.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["cold-white-balance", "unique", "stylized", "deep-blue-green-cast", "experimental", "moody", "atmospheric"],
        "whiteBalance": "9900K, B6-M0.5",
        "settings": { "Black level": "+4", "Gamma": "S-Cinetone", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+8", "Color Phase": "+1" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "-4", "C": "-4", "M": "-5", "Y": "+3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-025",
        "name": "SCL-025: Saturated Cinema",
        "description": "A powerful, high-saturation cinematic style, distinct from Fuji emulations.\nIt utilizes a wide color space to produce deep, rich colors with a filmic gamma curve, well-suited for vivid visual storytelling.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["high-saturation", "powerful-cinematic", "wide-color-space", "deep-rich-colors", "cinematic-gamma-curve", "vivid-visual-storytelling"],
        "whiteBalance": "4000K, A7-M1",
        "settings": { "Black level": "-5", "Gamma": "Cine4", "Black Gamma": "Wide -5", "Knee": "Manual 87.5% +3", "Color Mode": "S-Gamut3", "Saturation": "+32", "Color Phase": "+6" },
        "colorDepth": { "R": "-3", "G": "-2", "B": "+3", "C": "+7", "M": "-3", "Y": "-2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-026",
        "name": "SCL-026: HDR Cinema",
        "description": "Leveraging HLG (Hybrid Log-Gamma), this formula captures wide dynamic range with high saturation.\nIt produces a vivid, impactful image that feels both cinematic and surreal, ideal for high-energy shots.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["hlg", "hybrid-log-gamma", "wide-dynamic-range", "high-saturation", "vivid", "impactful", "cinematic-feel", "surreal", "high-energy-shots"],
        "whiteBalance": "3500K, A7",
        "settings": { "Black level": "-15", "Gamma": "HLG3", "Black Gamma": "Wide 0", "Knee": "Auto", "Color Mode": "BT.2020", "Saturation": "+32", "Color Phase": "+7" },
        "colorDepth": { "R": "-4", "G": "-1", "B": "+7", "C": "+6", "M": "+5", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-027",
        "name": "SCL-027: Daylight Cinema",
        "description": "A modern, clean cinematic style based on S-Cinetone.\nIt's designed for daylight conditions, delivering beautiful skin tones, high saturation, and a professional, polished feel straight out of camera.",
        "type": "color",
        "contrast": "normal",
        "saturation": "high",
        "tags": ["modern-cinematic", "clean", "s-cinetone", "daylight", "beautiful-skin-tones", "high-saturation", "professional", "polished", "straight-out-of-camera"],
        "whiteBalance": "3700K, A5-M1.5",
        "settings": { "Black level": "-9", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +5", "Color Mode": "S-Cinetone", "Saturation": "+25", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "+3", "B": "+2", "C": "+2", "M": "-3", "Y": "-3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-028",
        "name": "SCL-028: Phoenix Fire",
        "description": "An experimental and powerful style with ultra-high saturation and pronounced warm tones.\nIt creates fiery reds and oranges, perfect for bold, abstract, and high-impact photography.",
        "type": "color",
        "contrast": "high",
        "saturation": "extreme",
        "tags": ["experimental", "powerful", "ultra-high-saturation", "pronounced-warm-tones", "fiery-reds", "oranges", "bold", "abstract", "high-impact"],
        "whiteBalance": "8500K, B3.5-G1",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 105% +5", "Color Mode": "S-Cinetone", "Saturation": "+32", "Color Phase": "+1" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "+2", "C": "+5", "M": "+5", "Y": "+5" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-029",
        "name": "SCL-029: Hollywood Cool",
        "description": "A balanced cinematic formula for tungsten lighting with a cool blue-green bias.\nBased on S-Cinetone, it delivers smooth tones and a sophisticated, professional look reminiscent of classic Hollywood films.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["balanced-cinematic", "tungsten-light", "cool-blue-green-bias", "s-cinetone", "smooth-tones", "sophisticated", "professional-look", "classic-hollywood"],
        "whiteBalance": "8200K, B4.5-G1.75",
        "settings": { "Black level": "-10", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+16", "Color Phase": "+2" },
        "colorDepth": { "R": "+5", "G": "+7", "B": "-6", "C": "-5", "M": "+7", "Y": "-4" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-030",
        "name": "SCL-030: Graphite Standard",
        "description": "A balanced, versatile monochrome style with a full tonal range and clean mid-tones.\nThis is a perfect starting point for black and white photography, delivering classic, timeless results for any subject.",
        "type": "bw",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["balanced-monochrome", "versatile", "full-tonal-range", "clean-midtones", "perfect-starting-point", "black-and-white", "classic", "timeless"],
        "whiteBalance": "AWB (Priority White)",
        "settings": { "Black level": "-11", "Gamma": "Still", "Black Gamma": "Middle -3", "Knee": "Manual 85% +5", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "+1", "B": "-1", "C": "+3", "M": "-3", "Y": "-1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-031",
        "name": "SCL-031: Obsidian Contrast",
        "description": "A dramatic, high-contrast monochrome style with inky blacks and crisp whites.\nIdeal for architectural details, powerful street photography, and making subjects stand out with impressive clarity.",
        "type": "bw",
        "contrast": "high",
        "saturation": "normal",
        "tags": ["dramatic-monochrome", "high-contrast", "inky-blacks", "crisp-whites", "architectural-details", "powerful-street-photography", "impressive-clarity"],
        "whiteBalance": "AWB (Priority White)",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 85% +5", "Color Mode": "Black & White", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "-4", "B": "-1", "C": "+2", "M": "-1", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-032",
        "name": "SCL-032: Newsprint Grit",
        "description": "A powerful, high-contrast style that emulates the feel of 'pushed' black and white film used by photojournalists.\nIt's grainy, sharp, and full of character, perfect for capturing raw, unedited moments.",
        "type": "bw",
        "contrast": "high",
        "saturation": "normal",
        "tags": ["powerful", "high-contrast", "pushed-black-and-white-film", "photojournalism", "grainy", "sharp", "character", "raw", "unedited-moments"],
        "whiteBalance": "5500K, A3-G2",
        "settings": { "Black level": "+5", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 77.5% +2", "Color Mode": "Black & White", "Saturation": "+24", "Color Phase": "0" },
        "colorDepth": { "R": "-4", "G": "-1", "B": "+6", "C": "+5", "M": "-3", "Y": "-3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-033",
        "name": "SCL-033: Silver Gelatin",
        "description": "A flat, soft-contrast profile with rich mid-tones and smooth transitions.\nIt emulates the look of a classic darkroom print on silver gelatin paper, ideal for fine-art portraits and subtle compositions.",
        "type": "bw",
        "contrast": "soft",
        "saturation": "normal",
        "tags": ["flat", "soft-contrast", "rich-midtones", "smooth-transitions", "classic-darkroom-print", "silver-gelatin-paper", "fine-art-portrait", "subtle-compositions"],
        "whiteBalance": "5500K, A3-G2",
        "settings": { "Black level": "+3", "Gamma": "Cine1", "Black Gamma": "Narrow +5", "Knee": "Manual 75% +3", "Color Mode": "Black & White", "Saturation": "+24", "Color Phase": "0" },
        "colorDepth": { "R": "+3", "G": "+3", "B": "+3", "C": "+2", "M": "+3", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-034",
        "name": "SCL-034: Crystal Clear",
        "description": "A clean, crisp, and cool-toned black and white style.\nIt features fine grain and high clarity, perfect for technical subjects, architecture, and portraits where detail is paramount.",
        "type": "bw",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["clean", "crisp", "cool-tone", "fine-grain", "high-clarity", "technical-subjects", "architecture", "detail-oriented-portraits"],
        "whiteBalance": "AWB, B3-G0.25",
        "settings": { "Black level": "-12", "Gamma": "Still", "Black Gamma": "Middle -7", "Knee": "Manual 82% +5", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "-7", "B": "+7", "C": "+7", "M": "+7", "Y": "-4" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-035",
        "name": "SCL-035: Classic Reportage",
        "description": "A versatile, medium-contrast style with a classic grain structure.\nThis is a black and white 'workhorse' choice, ideal for photojournalism, street photography, and capturing everyday life with an authentic feel.",
        "type": "bw",
        "contrast": "medium",
        "saturation": "normal",
        "tags": ["versatile", "medium-contrast", "classic-grain", "black-and-white-workhorse", "photojournalism", "street-photography", "everyday-life", "authentic-feel"],
        "whiteBalance": "AWB, A3",
        "settings": { "Black level": "-12", "Gamma": "Movie", "Black Gamma": "Middle -5", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "0" },
        "colorDepth": { "R": "0", "G": "+3", "B": "0", "C": "+2", "M": "+3", "Y": "0" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-036",
        "name": "SCL-036: Noir Film",
        "description": "A very high-contrast, dramatic black and white style with deep, crushed blacks and bright whites.\nIt evokes the classic film noir aesthetic, perfect for creating mystery, drama, and graphic compositions.",
        "type": "bw",
        "contrast": "very-high",
        "saturation": "normal",
        "tags": ["very-high-contrast", "dramatic", "deep-crushed-blacks", "bright-whites", "classic-film-noir", "mystery", "graphic-compositions"],
        "whiteBalance": "5500K",
        "settings": { "Black level": "-15", "Gamma": "Still", "Black Gamma": "Wide -7", "Knee": "Manual 75% +4", "Color Mode": "Black & White", "Saturation": "+32", "Color Phase": "0" },
        "colorDepth": { "R": "+2", "G": "+7", "B": "+1", "C": "+2", "M": "+7", "Y": "+1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-037",
        "name": "SCL-037: Low Light Grain",
        "description": "Designed to emulate high-speed film, this formula uses a cinematic gamma to handle contrast while encouraging grain.\nIt's perfect for low-light situations, adding texture and atmosphere to shots.",
        "type": "bw",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["high-speed-film-emulation", "cinematic-gamma", "contrast-handling", "grain-encouraged", "low-light-situations", "texture", "atmosphere"],
        "whiteBalance": "AWB (Priority White)",
        "settings": { "Black level": "-11", "Gamma": "Cine4", "Black Gamma": "Wide +7", "Knee": "Manual 82.5% +0", "Color Mode": "Black & White", "Saturation": "0", "Color Phase": "-2" },
        "colorDepth": { "R": "+3", "G": "+2", "B": "+7", "C": "+7", "M": "+4", "Y": "-5" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-038",
        "name": "SCL-038: Modern B&W",
        "description": "A contemporary black and white style that utilizes S-Cinetone gamma for smooth, beautiful tonal transitions.\nIt delivers deep blacks without being overly harsh, well-suited for modern portraits and fine art.",
        "type": "bw",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["contemporary-black-and-white", "s-cinetone-gamma", "smooth-beautiful-tonal-transitions", "deep-blacks", "not-harsh", "modern-portrait", "fine-art"],
        "whiteBalance": "5500K",
        "settings": { "Black level": "-15", "Gamma": "S-Cinetone", "Black Gamma": "Narrow -7", "Knee": "Manual 75% +2", "Color Mode": "Black & White", "Saturation": "+28", "Color Phase": "0" },
        "colorDepth": { "R": "-3", "G": "+4", "B": "+3", "C": "+3", "M": "+3", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-039",
        "name": "SCL-039: Ortho Portrait",
        "description": "Emulating orthochromatic film, which is insensitive to red light.\nThis results in darkened skin and lip tones, creating a unique, vintage, and often dramatic portrait style.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["orthochromatic-film", "red-light-insensitive", "darkened-skin-tones", "lips", "unique-portrait", "vintage", "dramatic"],
        "whiteBalance": "AWB, A3-M2.75",
        "settings": { "Black level": "-12", "Gamma": "Movie", "Black Gamma": "Narrow -7", "Knee": "Manual 105% +5", "Color Mode": "Still", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "+7", "G": "+7", "B": "-7", "C": "-7", "M": "+7", "Y": "+7" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-040",
        "name": "SCL-040: Sunbath",
        "description": "Based on the unique film style, this recipe offers a creative and unpredictable look with distinct color shifts, especially in reds and greens. It's perfect for photographers looking to experiment with a quirky, analog-inspired palette.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["film-emulation", "analog-inspired", "quirky", "experimental", "color-shift"],
        "whiteBalance": "AWB, A5-G0.5",
        "settings": { "Black level": "-7", "Gamma": "Cine3", "Black Gamma": "Narrow -7", "Knee": "Manual 95% +4", "Color Mode": "Still", "Saturation": "+15", "Color Phase": "+2" },
        "colorDepth": { "R": "+3", "G": "+7", "B": "-5", "C": "-5", "M": "+4", "Y": "+4" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-041",
        "name": "SCL-041: Aya",
        "description": "A highly stylized and atmospheric recipe with a dominant, warm yellow-green cast. It dramatically transforms landscapes and scenes, creating a surreal, vintage, or even dystopian feel. Ideal for bold artistic statements.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["stylized", "atmospheric", "yellow-green-cast", "surreal", "vintage", "dystopian", "artistic"],
        "whiteBalance": "8000K, A7-G5.5",
        "settings": { "Black level": "-12", "Gamma": "Cine4", "Black Gamma": "Middle -7", "Knee": "Manual 75% +4", "Color Mode": "S-Gamut3", "Saturation": "+32", "Color Phase": "+7" },
        "colorDepth": { "R": "+4", "G": "+5", "B": "0", "C": "0", "M": "-3", "Y": "+7" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-042",
        "name": "SCL-42: Kando 25 Phuket",
        "description": "Capture Phuket's cinematic soul. This S-Cinetone formula delivers a filmic look with lush greens, vibrant turquoise waters, and warm golden light, perfect for Thailand's tropical paradise.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["stylized", "atmospheric", "yellow-green-cast", "surreal", "vintage", "dystopian", "artistic"],
        "whiteBalance": "8000K, B7-G0.5",
        "settings": { "Black level": "-11", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+12", "Color Phase": "-1" },
        "colorDepth": { "R": "-2", "G": "+4", "B": "+4", "C": "+5", "M": "-2", "Y": "-3" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-043",
        "name": "SCL-43: Macro shooting for Tran Anh Tuan",
        "description": "A color recipe with natural and vivid colors, suitable for Macro photography in the style of Photographer Tran Anh Tuan.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["stylized", "atmospheric", "macro", "surreal", "contemporary", "artistic"],
        "whiteBalance": "AWB, B1-G0.5",
        "settings": { "Black level": "-5", "Gamma": "Movie", "Black Gamma": "Middle -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+10", "Color Phase": "-1" },
        "colorDepth": { "R": "+2", "G": "+2", "B": "+2", "C": "0", "M": "0", "Y": "0" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
    {
        "id": "scl-044",
        "name": "SCL-44: Filmic FJ C200",
        "description": "A filmic recipe that mimic FJ C200 Film stock.",
        "type": "color",
        "contrast": "high",
        "saturation": "high",
        "tags": ["stylized", "atmospheric", "macro", "surreal", "contemporary", "artistic"],
        "whiteBalance": "AWB, B1-G0.5",
        "settings": { "Black level": "+5", "Gamma": "Cine4", "Black Gamma": "Narrow +5", "Knee": "Manual 75% +5", "Color Mode": "S-Gamut3.Cine", "Saturation": "+20", "Color Phase": "-2" },
        "colorDepth": { "R": "+2", "G": "-3", "B": "+3", "C": "-4", "M": "+1", "Y": "-2" },
        "detailSettings": {
            level: -5,
            mode: "Manual",
            vhBalance: "-22",
            bwBalance: "Type 1",
            limit: 3,
            crispening: 3,
            hiLightDetail: 2
        }
    },
    {
        "id": "scl-1001",
        "name": "SCL-1001: ClearCast Pro",
        "description": "A color recipe for crystal-clear images, featuring rich colors on a neutral foundation. Specially designed for livestreaming, it renders Asian skin tones authentically and radiantly.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["pro-color", "live-stream", "neutral", "lips", "portrait", "color", "high-contrast", "crystal-clear"],
        "whiteBalance": "AWB, B1-M0.75",
        "settings": { "Black level": "-5", "Gamma": "S-Cinetone", "Black Gamma": "Wide -7", "Knee": "Auto", "Color Mode": "S-Cinetone", "Saturation": "+8", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "-1", "B": "+1", "C": "+1", "M": "+1", "Y": "-1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
      {
        "id": "scl-1002",
        "name": "SCL-1002: ClearCast Pro 2",
        "description": "A color recipe for crystal-clear images, featuring rich colors on a neutral foundation. Specially designed for livestreaming, it renders Asian skin tones authentically and radiantly.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["pro-color", "live-stream", "neutral", "lips", "portrait", "color", "high-contrast", "crystal-clear"],
        "whiteBalance": "AWB, B1-M0.75",
        "settings": { "Black level": "-3", "Gamma": "Movie", "Black Gamma": "Wide -7", "Knee": "Auto", "Color Mode": "Still", "Saturation": "+8", "Color Phase": "0" },
        "colorDepth": { "R": "-1", "G": "-1", "B": "+1", "C": "+1", "M": "+1", "Y": "-1" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
    },
          {
        "id": "scl-1003",
        "name": "SCL-1003: EXTRA DR Stream 109",
        "description": "A color recipe for crystal-clear images, featuring rich colors on a neutral foundation. Specially designed for livestreaming, it renders Asian skin tones authentically and radiantly.",
        "type": "color",
        "contrast": "normal",
        "saturation": "normal",
        "tags": ["pro-color", "live-stream", "neutral", "lips", "portrait", "color", "high-contrast", "crystal-clear"],
        "whiteBalance": "AWB, B1-M0.75",
        "settings": { "Black level": "-3", "Gamma": "Cine1", "Black Gamma": "Wide -7", "Knee": "Manual 105% +2", "Color Mode": "Movie", "Saturation": "+15", "Color Phase": "0" },
        "colorDepth": { "R": "-2", "G": "-5", "B": "+3", "C": "+3", "M": "-4", "Y": "+2" },
        "detailSettings": {
            level: 0,
            mode: "Manual",
            vhBalance: "+2",
            bwBalance: "Type 3",
            limit: 3,
            crispening: 7,
            hiLightDetail: 4
        }
          }
];

export default recipesData;
